[package]
name = "kinair-selection-software"
version = "16.0.0"
description = "KINAIR fan and air curtain selection software"
authors = ["KINAIR"]
edition = "2021"

[lib]
name = "kinair_selection_software_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
