import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PDFDocument } from 'pdf-lib';
import * as tus from 'tus-js-client';
import { AlertTriangle, CheckCircle2, FileSearch, GripVertical, Loader2, Plus, RotateCcw, Sparkles, Trash2, UploadCloud, XCircle } from 'lucide-react';
import { supabase } from '@/integrations/backend/client';
import { useAuth } from '@/lib/authContext';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { SubmittalAttachments } from '@/components/submittal/SubmittalAttachments';
import { SubmittalTemplates } from '@/components/submittal/SubmittalFiles';

const db=supabase as any;
const BUCKET='submittal-control';
const MAX_SOURCE_BYTES=250*1024*1024;
const DIRECT_ANALYSIS_BYTES=15*1024*1024;
function toBase64(bytes:Uint8Array){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function makeAnalysisPdf(file:File){const source=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true});const preview=await PDFDocument.create();const indices=source.getPageIndices().slice(0,Math.min(15,source.getPageCount()));const pages=await preview.copyPages(source,indices);pages.forEach(page=>preview.addPage(page));const bytes=await preview.save({useObjectStreams:true});if(bytes.length>=50*1024*1024)throw new Error('The first 15 pages exceed the AI analysis limit. Upload a separate cover/index PDF.');return bytes}
async function resumableUpload(file:File,path:string){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sign in required');const projectId=new URL(import.meta.env.VITE_SUPABASE_URL).hostname.split('.')[0];await new Promise<void>((resolve,reject)=>{const upload=new tus.Upload(file,{endpoint:`https://${projectId}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,3000,5000,10000,20000],headers:{authorization:`Bearer ${session.access_token}`},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:BUCKET,objectName:path,contentType:file.type||'application/pdf',cacheControl:'3600'},onError:reject,onSuccess:()=>resolve()});upload.findPreviousUploads().then(previous=>{if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start()}).catch(reject)})}
const MATERIAL_INDEX=['Company Profile','Trade License','Certificates','Authorization Letter','Project Specification','Compliance Statement','List of Materials / BOQ','Product Catalogue','Test Reports','Method Statement','Estidama Form','Warranty Certificate','Country of Origin','Previous Material Approvals / Project List'];
const DEFAULT_INDEXES={regular:MATERIAL_INDEX.join('\n'),pq:['Prequalification Letter','Company Profile','Trade License','Organization Chart','Certificates','Authorization Letter','Product Catalogue','Test Reports','Project Reference List'].join('\n'),om:['O&M Cover Letter','Approved Material Submittal','Approved Material Schedule','Product Datasheets','Technical Drawings','Installation Manual','Operation Manual','Maintenance Instructions','Testing & Commissioning Records','Warranty Certificate','Spare Parts List','Contact Details'].join('\n')} as const;
const DEFAULT_INDEX=DEFAULT_INDEXES.regular;
const FAN_INDEX=['Company Profile','Trade License','Certificates','Compliance Statement','Material Schedule','Fan Datasheets','Technical Drawings','Performance Curves','Acoustic Data','Test Reports','Warranty Certificate','Country of Origin','Project Reference List'].join('\n');
const AIR_CURTAIN_INDEX=['Company Profile','Trade License','Certificates','Compliance Statement','Material Schedule','Air Curtain Datasheets','Technical Drawings','Installation Details','Performance Data','Test Reports','Warranty Certificate','Country of Origin','Project Reference List'].join('\n');
const AIR_HANDLING_INDEX=['Company Profile','Trade License','Certificates','Compliance Statement','Equipment Schedule','Selection Data','Unit Datasheets','Certified Technical Drawings','Fan & Motor Data','Coil Selection','Filter Data','Acoustic Data','Control Sequence','Installation Requirements','Test Reports','Warranty Certificate','Country of Origin','Project Reference List'].join('\n');
const ECOLOGY_INDEX=['Company Profile','Trade License','Certificates','Compliance Statement','Equipment Schedule','Selection Data','Unit Datasheets','Certified Technical Drawings','ESP Cell Data','Filtration Stages','Fan & Motor Data','Control Sequence','Installation Requirements','Test Reports','Warranty Certificate','Country of Origin','Project Reference List'].join('\n');
const SERIES=[{name:'KVF-P',brand:'KINAIR',family:'Fan'},{name:'KVF-M',brand:'KINAIR',family:'Fan'},{name:'KVF-MR',brand:'KINAIR',family:'Fan'},{name:'KIN-E',brand:'KINAIR',family:'Fan'},{name:'KTAF',brand:'KINAIR',family:'Fan'},{name:'N-Cross Flow',brand:'KINAIR',family:'Air Curtain'},{name:'N-Centrifugal Flow',brand:'KINAIR',family:'Air Curtain'},{name:'XD-Centrifugal Flow',brand:'KINAIR',family:'Air Curtain'},{name:'VVS',brand:'VTS Clima',family:'AHU / FAHU / MAHU / Ecology'},{name:'WING',brand:'VTS Clima',family:'Air Curtain'}] as const;
const PRESETS=[
 {name:'Standard Material',type:'regular' as const,brand:'KINAIR',material:'Material Submittal',index:DEFAULT_INDEXES.regular},
 {name:'KINAIR Fan',type:'regular' as const,brand:'KINAIR',material:'Ventilation Fans',series:['KVF-P','KVF-M','KVF-MR','KIN-E','KTAF'],index:FAN_INDEX},
 {name:'KINAIR Air Curtain',type:'regular' as const,brand:'KINAIR',material:'Air Curtain Units',series:['N-Cross Flow','N-Centrifugal Flow','XD-Centrifugal Flow'],index:AIR_CURTAIN_INDEX},
 {name:'VTS Clima Air Curtain',type:'regular' as const,brand:'VTS Clima',material:'Air Curtain Units',series:['WING'],index:AIR_CURTAIN_INDEX},
 {name:'VTS Clima AHU',type:'regular' as const,brand:'VTS Clima',material:'Air Handling Units (AHU)',series:['VVS'],index:AIR_HANDLING_INDEX},
 {name:'VTS Clima FAHU',type:'regular' as const,brand:'VTS Clima',material:'Fresh Air Handling Units (FAHU)',series:['VVS'],index:AIR_HANDLING_INDEX},
 {name:'VTS Clima MAHU',type:'regular' as const,brand:'VTS Clima',material:'Make-up Air Handling Units (MAHU)',series:['VVS'],index:AIR_HANDLING_INDEX},
 {name:'VTS Clima Ecology',type:'regular' as const,brand:'VTS Clima',material:'Ecology Units',series:['VVS'],index:ECOLOGY_INDEX},
 {name:'Company PQ',type:'pq' as const,brand:'KINAIR',material:'Company Prequalification',index:DEFAULT_INDEXES.pq},
 {name:'Standard O&M',type:'om' as const,brand:'KINAIR',material:'Operation & Maintenance Manual',index:DEFAULT_INDEXES.om},
] as const;
type IndexSection={id?:string;name:string;source_label?:string;sort_order:number};
const COVER_FIELDS=[['project_name','Project Name'],['material','Material / Submittal For'],['client_name','Client Name'],['consultant_name','MEP Consultant'],['main_contractor_name','Main Contractor'],['subcontractor_name','MEP Contractor'],['supplier_name','Supplier Name'],['brand_name','Brand Name']] as const;
const PACKAGE_COLUMNS=new Set(['project_name','material','client_name','consultant_name','main_contractor_name','subcontractor_name']);
const packageCover=(p:any)=>Object.fromEntries(COVER_FIELDS.map(([key])=>[key,p?.cover_details?.[key]??p?.[key]??(key==='supplier_name'?'KINETICS MIDDLE EAST LLC':key==='brand_name'?'KINAIR':'')]));
const packageLabels=(p:any)=>Object.fromEntries(COVER_FIELDS.map(([key,label])=>[key,p?.cover_details?.field_labels?.[key]??label]));
const packageAdditional=(p:any)=>(Array.isArray(p?.cover_details?.additional_fields)?p.cover_details.additional_fields:[]).map((x:any)=>`${x.label||''}: ${x.value||''}`).join('\n');
const packageTemplates=(p:any)=>({cover:p?.cover_details?.template_ids?.cover||'',index:p?.cover_details?.template_ids?.index||'',divider:p?.cover_details?.template_ids?.divider||'',logo:p?.cover_details?.template_ids?.logo||''});
const parseAdditional=(value:string)=>value.split(/\r?\n/).map(line=>{const split=line.indexOf(':');return split<0?{label:line.trim(),value:''}:{label:line.slice(0,split).trim(),value:line.slice(split+1).trim()}}).filter(x=>x.label);
const inferSeries=(value:string)=>{const v=value.toUpperCase();if(v.includes('KVF-MR'))return 'KVF-MR';if(v.includes('KVF-P'))return 'KVF-P';if(v.includes('KVF-M'))return 'KVF-M';if(v.includes('KIN-E'))return 'KIN-E';if(v.includes('KTAF'))return 'KTAF';if(v.includes('WING'))return 'WING';if(v.includes('VVS'))return 'VVS';if(v.includes('XD')||v.includes('FM35')||v.includes('FM45')||v.includes('FM55'))return 'XD-Centrifugal Flow';if(v.includes('FM-12')||v.includes('N-2'))return 'N-Cross Flow';if(v.includes('N-CENTRIFUGAL'))return 'N-Centrifugal Flow';return ''};
const normalize=(v:string)=>v.toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim();
const aliases:Record<string,string[]>={
 'company profile':['company profile'],
 'trade license':['trade license','commercial license'],
 'certificates':['certificates','certificate','ce certificate','cb certificate'],
 'authorization letter':['authorization letter','authorisation letter'],
 'project specification':['project specification','specification'],
 'compliance statement':['compliance statement','compliance statment'],
 'list of materials boq':['list of materials','boq','material schedule','equipment schedule'],
 'product catalogue':['product catalogue','product catalog','product data','technical data','datasheet'],
 'test reports':['test reports','test report'],
 'method statement':['method statement','method statment'],
 'estidama form':['estidama','sustainability'],
 'warranty certificate':['warranty certificate','warranty'],
 'country of origin':['country of origin','origin certificate'],
 'previous material approvals project list':['previous material approvals','previous approvals','project list','reference projects'],
};
const canonical=(name:string)=>{const n=normalize(name);return Object.entries(aliases).find(([,terms])=>terms.some(t=>n.includes(normalize(t))||normalize(t).includes(n)))?.[0]||n};
const parseIndex=(value:string):IndexSection[]=>value.split(/\r?\n/).map(v=>v.replace(/^\s*\d+[.)-]?\s*/,'').replace(/\s+\d+\s*$/,'').trim()).filter(Boolean).map((name,sort_order)=>({id:crypto.randomUUID(),name,source_label:name,sort_order}));

export function AdvancedSubmittalBuilder(){
 const {user,tenantId}=useAuth();const {toast}=useToast();const qc=useQueryClient();
 const [packageId,setPackageId]=useState('');const [scheduleResult,setScheduleResult]=useState<any>(null);const [chosenSeries,setChosenSeries]=useState<Set<string>>(new Set());const [autosaveReady,setAutosaveReady]=useState(false);const [packageType,setPackageType]=useState<'regular'|'pq'|'om'>('regular');const [sourceText,setSourceText]=useState('');const [templateIds,setTemplateIds]=useState<Record<'cover'|'index'|'divider'|'logo',string>>({cover:'',index:'',divider:'',logo:''});const [dragIndex,setDragIndex]=useState<number|null>(null);const [newSection,setNewSection]=useState('');const [indexText,setIndexText]=useState(DEFAULT_INDEX);const [coverDetails,setCoverDetails]=useState<Record<string,string>>({});const [coverLabels,setCoverLabels]=useState<Record<string,string>>(Object.fromEntries(COVER_FIELDS));const [additionalFieldsText,setAdditionalFieldsText]=useState('');const [loadedVersion,setLoadedVersion]=useState(1);const [selectedModels,setSelectedModels]=useState<Set<string>>(new Set());const [result,setResult]=useState<any>(null);
 const packages=useQuery({queryKey:['advanced-submittal-packages',tenantId],enabled:!!tenantId,queryFn:async()=>{const {data,error}=await db.from('submittal_packages').select('*').eq('tenant_id',tenantId).order('created_at',{ascending:false});if(error)throw error;return data??[]}});
 const templates=useQuery({queryKey:['submittal_templates',tenantId],enabled:!!tenantId,queryFn:async()=>{const {data,error}=await db.from('submittal_templates').select('*').eq('tenant_id',tenantId).order('created_at',{ascending:false});if(error)throw error;return data??[]}});
 const products=useQuery({queryKey:['advanced-submittal-products',tenantId],enabled:!!tenantId,queryFn:async()=>{const {data,error}=await db.from('submittal_products').select('id,name,submittal_product_models(id,name,code)').eq('tenant_id',tenantId).order('name');if(error)throw error;return data??[]}});
 const selectedPackage=packages.data?.find((p:any)=>p.id===packageId);
 const modelMap=useMemo(()=>new Map((products.data??[]).flatMap((p:any)=>p.submittal_product_models.map((m:any)=>[m.id,{...m,product_id:p.id,product_name:p.name,series:inferSeries([m.code,m.name,p.name].filter(Boolean).join(' '))}]))),[products.data]);

 function choosePackage(id:string){setPackageId(id);const p=packages.data?.find((x:any)=>x.id===id);setPackageType(p?.package_type||'regular');setCoverDetails(packageCover(p));setCoverLabels(packageLabels(p));setAdditionalFieldsText(packageAdditional(p));setTemplateIds(packageTemplates(p));setChosenSeries(new Set(Array.isArray(p?.cover_details?.selected_series)?p.cover_details.selected_series:[]));setLoadedVersion(p?.version||1);if(Array.isArray(p?.index_sections)&&p.index_sections.length)setIndexText(p.index_sections.map((x:any)=>x.name).join('\n'));else setIndexText(DEFAULT_INDEX);setResult(p?.validation_report?.assembly||null);void loadSelections(id)}
 async function loadSelections(id:string){const {data}=await db.from('submittal_package_products').select('model_id').eq('package_id',id);setSelectedModels(new Set((data??[]).map((x:any)=>x.model_id).filter(Boolean)))}
 function applyPreset(p:(typeof PRESETS)[number]){setPackageType(p.type);setCoverDetails(prev=>({...prev,brand_name:p.brand,material:p.material}));setChosenSeries(new Set('series' in p?p.series:[]));setIndexText(p.index);setResult(null);toast({title:p.name+' preset applied',description:'Index, dividers and document rules are ready to review.'})}
 function moveSection(from:number,to:number){if(from===to||from<0||to<0)return;const rows=parseIndex(indexText);const [moved]=rows.splice(from,1);rows.splice(to,0,moved);setIndexText(rows.map(x=>x.name).join('\n'))}
 function updateSection(i:number,value:string){const rows=parseIndex(indexText);rows[i].name=value;setIndexText(rows.map(x=>x.name).join('\n'))}
 function removeSection(i:number){setIndexText(parseIndex(indexText).filter((_,n)=>n!==i).map(x=>x.name).join('\n'))}
 function addSection(){const name=newSection.trim();if(!name)return;setIndexText([...parseIndex(indexText).map(x=>x.name),name].join('\n'));setNewSection('')}
 function toggle(id:string){setSelectedModels(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n})}
 async function ensurePackage(title='New submittal'){if(packageId)return packageId;if(!user||!tenantId)throw new Error('Sign in required');const {data:draft,error}=await db.from('submittal_packages').insert({tenant_id:tenantId,package_type:packageType,status:'draft',project_name:title,material:packageType==='om'?'O&M Manual':packageType==='pq'?'Prequalification':'Material Submittal',submission_date:new Date().toISOString().slice(0,10),cover_details:{supplier_name:'KINETICS MIDDLE EAST LLC',brand_name:'KINAIR',field_labels:Object.fromEntries(COVER_FIELDS)},created_by:user.id,updated_by:user.id}).select('*').single();if(error)throw error;setPackageId(draft.id);setCoverDetails(packageCover(draft));setCoverLabels(packageLabels(draft));setLoadedVersion(draft.version||1);await qc.invalidateQueries({queryKey:['advanced-submittal-packages']});toast({title:'Draft workspace created',description:'You can now complete cover, index and documents together.'});return draft.id}
 function applyAnalysis(data:any){const extracted=Object.fromEntries(Object.entries(data.cover??{}).filter(([,value])=>typeof value==='string'&&value.trim()));setCoverDetails(prev=>({...prev,...extracted}));if(Array.isArray(data.cover?.additional_fields))setAdditionalFieldsText(data.cover.additional_fields.filter((x:any)=>x?.label).map((x:any)=>`${x.label}: ${x.value||''}`).join('\n'));if(data.sections?.length)setIndexText(data.sections.map((x:any)=>x.name).join('\n'));toast({title:'Cover and index read',description:`${data.sections?.length||0} sections detected. Review and edit before building.`});void qc.invalidateQueries({queryKey:['advanced-submittal-packages']})}

 const analyze=useMutation({mutationFn:async({file,targetPackageId}:{file:File;targetPackageId:string})=>{if(!user||!tenantId)throw new Error('Sign in required');if(file.size>MAX_SOURCE_BYTES)throw new Error('Cover/index file must be 250 MB or smaller');const path=`${tenantId}/customer-input/${targetPackageId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;let fileData:string;let sourceAlreadyUploaded=false;if(file.size<=DIRECT_ANALYSIS_BYTES){fileData=toBase64(new Uint8Array(await file.arrayBuffer()))}else{await resumableUpload(file,path);sourceAlreadyUploaded=true;fileData=toBase64(await makeAnalysisPdf(file))}const {data,error}=await supabase.functions.invoke('submittal-analyze',{body:{packageId:targetPackageId,storagePath:path,fileName:file.name,mimeType:file.type,fileData,sourceAlreadyUploaded}});if(error)throw error;return data},onSuccess:applyAnalysis});
 async function uploadSource(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!user||!tenantId)return;try{const targetPackageId=await ensurePackage(file.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ').trim()||'New submittal');await analyze.mutateAsync({file,targetPackageId})}catch(x){toast({title:'Unable to read document',description:x instanceof Error?x.message:'Please retry',variant:'destructive'})}finally{e.target.value=''}}
 const analyzePasted=useMutation({mutationFn:async()=>{if(!sourceText.trim())throw new Error('Paste the customer email, cover details or index first');const targetPackageId=await ensurePackage(sourceText.trim().split(/\r?\n/)[0].slice(0,100)||'New submittal');const {data,error}=await supabase.functions.invoke('submittal-analyze',{body:{packageId:targetPackageId,sourceText:sourceText.trim()}});if(error)throw error;return data},onSuccess:applyAnalysis,onError:x=>toast({title:'Unable to read pasted details',description:x instanceof Error?x.message:'Please retry',variant:'destructive'})});
 const analyzeSchedule=useMutation({mutationFn:async(file:File)=>{if(file.size>15*1024*1024)throw new Error('Material schedule must be 15 MB or smaller');const targetPackageId=await ensurePackage(file.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ').trim()||'Material schedule');const availableModels=[...modelMap.values()].map((m:any)=>({id:m.id,code:m.code,name:m.name,product:m.product_name,series:m.series}));const fileData=toBase64(new Uint8Array(await file.arrayBuffer()));const {data,error}=await supabase.functions.invoke('submittal-schedule-analyze',{body:{packageId:targetPackageId,fileName:file.name,mimeType:file.type,fileData,availableModels}});if(error)throw error;return data},onSuccess:data=>{setSelectedModels(prev=>new Set([...prev,...(data.matched_model_ids??[])]));setChosenSeries(prev=>new Set([...prev,...(data.matched_series??[])]));const brands=new Set((data.matched_series??[]).map((series:string)=>SERIES.find(s=>s.name===series)?.brand).filter(Boolean));if(brands.size)setCoverDetails(prev=>({...prev,brand_name:[...brands].join(' / ')}));setScheduleResult(data);toast({title:'Material schedule matched',description:`${data.matched_model_ids?.length||0} model(s) · ${data.matched_series?.length||0} series selected`})},onError:x=>toast({title:'Schedule reading failed',description:x instanceof Error?x.message:'Please retry',variant:'destructive'})});
 async function uploadSchedule(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{await analyzeSchedule.mutateAsync(file)}finally{e.target.value=''}}

 useEffect(()=>{if(!packageId)return;const channel=supabase.channel(`submittal-workspace-${packageId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'submittal_packages',filter:`id=eq.${packageId}`},({new:next}:any)=>{if((next.version||1)>loadedVersion){setLoadedVersion(next.version||1);setPackageType(next.package_type||'regular');setCoverDetails(packageCover(next));setCoverLabels(packageLabels(next));setAdditionalFieldsText(packageAdditional(next));setTemplateIds(packageTemplates(next));setChosenSeries(new Set(Array.isArray(next?.cover_details?.selected_series)?next.cover_details.selected_series:[]));if(Array.isArray(next.index_sections)&&next.index_sections.length)setIndexText(next.index_sections.map((x:any)=>x.name).join('\n'));toast({title:'Workspace updated by another user',description:'The latest cover and index are now shown.'})}}).subscribe();return()=>{void supabase.removeChannel(channel)}},[packageId,loadedVersion,toast]);

 const saveWorkspace=useMutation({mutationFn:async()=>{if(!user||!packageId)throw new Error('Select a package');const sections=parseIndex(indexText);const nextVersion=loadedVersion+1;const packageColumns=Object.fromEntries(Object.entries(coverDetails).filter(([key])=>PACKAGE_COLUMNS.has(key)));const {data,error}=await db.from('submittal_packages').update({...packageColumns,package_type:packageType,cover_details:{...coverDetails,field_labels:coverLabels,additional_fields:parseAdditional(additionalFieldsText),template_ids:templateIds,selected_series:[...chosenSeries]},index_sections:sections,version:nextVersion,editing_by:user.id,editing_at:new Date().toISOString(),updated_by:user.id,updated_at:new Date().toISOString()}).eq('id',packageId).eq('version',loadedVersion).select('version').maybeSingle();if(error)throw error;if(!data)throw new Error('Another user changed this package. Latest values have been loaded; review and save again.');return data.version},onSuccess:version=>{setLoadedVersion(version);toast({title:'Shared workspace saved',description:'Cover, index and divider plan saved together.'})}});
 useEffect(()=>{setAutosaveReady(false);const timer=window.setTimeout(()=>setAutosaveReady(true),900);return()=>window.clearTimeout(timer)},[packageId]);
 useEffect(()=>{if(!packageId||!autosaveReady||saveWorkspace.isPending)return;const timer=window.setTimeout(()=>saveWorkspace.mutate(),1400);return()=>window.clearTimeout(timer)},[packageType,coverDetails,coverLabels,additionalFieldsText,indexText,templateIds,chosenSeries,packageId]);

 const build=useMutation({mutationFn:async()=>{
  if(!user||!tenantId||!packageId)throw new Error('Select a package');const sections=parseIndex(indexText);if(!sections.length)throw new Error('Enter at least one index section');
  const selected=[...selectedModels].map(id=>modelMap.get(id)).filter(Boolean) as any[];
  await db.from('submittal_package_products').delete().eq('package_id',packageId);
  if(selected.length){const {error}=await db.from('submittal_package_products').insert(selected.map(m=>({tenant_id:tenantId,package_id:packageId,product_id:m.product_id,model_id:m.id,created_by:user.id})));if(error)throw error}
  const {data:docs,error:docError}=await db.from('submittal_documents').select('*').eq('tenant_id',tenantId).eq('is_active',true);if(docError)throw docError;
  const {data:uploads,error:uploadError}=await db.from('submittal_attachments').select('*').eq('package_id',packageId).order('sort_order');if(uploadError)throw uploadError;
  const selectedProductIds=new Set(selected.map(m=>m.product_id));const selectedModelIds=new Set(selected.map(m=>m.id));const selectedSeries=new Set([...chosenSeries,...selected.map(m=>m.series).filter(Boolean)].map(normalize));
  const applicable=(d:any)=>d.scope_type==='company'||(d.scope_type==='project'&&d.package_id===packageId)||(d.scope_type==='product'&&selectedProductIds.has(d.product_id))||(d.scope_type==='model'&&selectedModelIds.has(d.model_id))||(d.scope_type==='series'&&selectedSeries.has(normalize(d.series_name||'')));
  const items:any[]=[];const summary:any[]=[];
  for(const section of sections){const key=canonical(section.name);const matches=(docs??[]).filter((d:any)=>{const terms=[d.category,d.display_name,...(d.keywords||[])].map((x:string)=>canonical(x||''));return applicable(d)&&terms.some((x:string)=>x===key||x.includes(key)||key.includes(x))}).sort((a:any,b:any)=>Number(Boolean(b.model_id))-Number(Boolean(a.model_id))||Number(Boolean(b.product_id))-Number(Boolean(a.product_id)));const projectFiles=(uploads??[]).filter((a:any)=>canonical(a.section_name||'')===key);
   for(const d of matches){const expired=d.expires_on&&new Date(d.expires_on)<new Date();items.push({tenant_id:tenantId,package_id:packageId,product_id:d.product_id,model_id:d.model_id,document_id:d.id,section_name:section.name,source_type:'library',display_name:d.display_name,storage_path:d.storage_path,sort_order:items.length,is_included:true,is_required:d.is_mandatory,validation_state:expired?'expired':'ready',notes:expired?'Document expiry date has passed':null})}
   for(const file of projectFiles)items.push({tenant_id:tenantId,package_id:packageId,section_name:section.name,source_type:'upload',display_name:file.display_name,storage_path:file.storage_path,sort_order:items.length,is_included:true,is_required:false,validation_state:'ready'});
   const names=[...matches.map((d:any)=>d.display_name),...projectFiles.map((a:any)=>a.display_name)];if(names.length)summary.push({section:section.name,state:matches.some((d:any)=>d.expires_on&&new Date(d.expires_on)<new Date())?'warning':'ready',documents:names});else{items.push({tenant_id:tenantId,package_id:packageId,section_name:section.name,source_type:'generated',display_name:'Missing document',sort_order:items.length,is_included:false,is_required:true,validation_state:'missing',notes:'Upload or map a document for this section'});summary.push({section:section.name,state:'missing',documents:[]})}}
  await db.from('submittal_package_items').delete().eq('package_id',packageId);const {error:itemError}=await db.from('submittal_package_items').insert(items);if(itemError)throw itemError;
  const report={assembly:summary,ready:summary.filter(x=>x.state==='ready').length,missing:summary.filter(x=>x.state==='missing').length,warnings:summary.filter(x=>x.state==='warning').length,checked_at:new Date().toISOString()};
  const nextVersion=loadedVersion+1;const {data:updated,error:updateError}=await db.from('submittal_packages').update({index_sections:sections,validation_report:report,version:nextVersion,editing_by:user.id,editing_at:new Date().toISOString(),updated_by:user.id,updated_at:new Date().toISOString()}).eq('id',packageId).eq('version',loadedVersion).select('version').maybeSingle();if(updateError)throw updateError;if(!updated)throw new Error('Another user changed this package. Review the latest workspace and build again.');return {...report,version:updated.version};
 },onSuccess:r=>{setLoadedVersion(r.version);setResult(r.assembly);toast({title:'Automatic package prepared',description:`${r.ready} ready · ${r.missing} missing · ${r.warnings} warnings`});void qc.invalidateQueries({queryKey:['submittal-package-register']})}});

 const revise=useMutation({mutationFn:async()=>{if(!user||!tenantId||!selectedPackage)throw new Error('Select a saved package');const {error:snapshotError}=await db.from('submittal_package_revisions').insert({tenant_id:tenantId,package_id:selectedPackage.id,revision:selectedPackage.revision,snapshot:selectedPackage,created_by:user.id});if(snapshotError)throw snapshotError;const {error:updateError}=await db.from('submittal_packages').update({revision:(selectedPackage.revision||0)+1,status:'draft',approval_status:'no_update',output_storage_path:null,updated_by:user.id,updated_at:new Date().toISOString()}).eq('id',selectedPackage.id);if(updateError)throw updateError},onSuccess:()=>{toast({title:`Revision R${(selectedPackage?.revision||0)+1} created`,description:'Previous revision preserved. Add consultant comments or replace only revised documents.'});void qc.invalidateQueries({queryKey:['advanced-submittal-packages']})}});
 const generate=useMutation({mutationFn:async()=>{if((result??[]).some((x:any)=>x.state==='missing'))throw new Error('Resolve missing sections before final generation');const {data,error}=await supabase.functions.invoke('submittal-pdf',{body:{packageId}});if(error)throw error;const blob=data instanceof Blob?data:new Blob([data],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${selectedPackage?.reference||'submittal'}-R${selectedPackage?.revision||0}.pdf`;a.click();URL.revokeObjectURL(a.href)},onSuccess:()=>toast({title:'Final submittal generated'})});
 const counts={ready:(result??[]).filter((x:any)=>x.state==='ready').length,missing:(result??[]).filter((x:any)=>x.state==='missing').length,warning:(result??[]).filter((x:any)=>x.state==='warning').length};
 return <div className="space-y-5">
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary"/>Unified Manual + AI Submittal Workspace</CardTitle><CardDescription>Provide only the customer cover/index and choose the proposed models. KINAIR maps the controlled documents and prepares the full package.</CardDescription></CardHeader><CardContent className="space-y-5">
   <div className="rounded-lg border p-4"><Label>Quick-start preset</Label><p className="mb-3 text-xs text-muted-foreground">Choose the brand and equipment family to fill Brand, Material and the correct document structure automatically.</p><div className="flex flex-wrap gap-2">{PRESETS.map(p=><Button key={p.name} type="button" variant="outline" size="sm" onClick={()=>applyPreset(p)}>{p.name}</Button>)}</div></div>
   <div className="grid gap-3 md:grid-cols-[1fr_240px]"><div><Label>Saved package</Label><select value={packageId} onChange={e=>choosePackage(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="">Start a new package or select existing</option>{packages.data?.map((p:any)=><option key={p.id} value={p.id}>{p.reference||'Draft'} · {p.project_name}</option>)}</select></div><div><Label>Submittal type</Label><select value={packageType} onChange={e=>{const type=e.target.value as 'regular'|'pq'|'om';setPackageType(type);if(!packageId)setIndexText(DEFAULT_INDEXES[type])}} className="h-10 w-full rounded-md border bg-background px-3"><option value="regular">Material Submittal</option><option value="pq">PQ / Prequalification</option><option value="om">O&amp;M Manual</option></select></div></div>
   <div className="rounded-lg border p-4"><Label>Paste customer email, cover details or index</Label><p className="mb-3 text-xs text-muted-foreground">Copy from an email or document. AI fills the cover and index below; every extracted value remains editable.</p><Textarea rows={6} value={sourceText} onChange={e=>setSourceText(e.target.value)} placeholder="Project: ...&#10;Client: ...&#10;Consultant: ...&#10;Index: 1. Company Profile ..."/><div className="mt-3 flex justify-end"><Button type="button" variant="secondary" disabled={!sourceText.trim()||analyzePasted.isPending} onClick={()=>analyzePasted.mutate()}>{analyzePasted.isPending&&<Loader2 className="h-4 w-4 animate-spin"/>}Read pasted details</Button></div></div>
   <div className="rounded-lg border p-4"><div className="mb-3 flex items-center justify-between"><div><Label>Shared cover-page details</Label><p className="text-xs text-muted-foreground">Enter manually or let AI populate these same editable fields.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">Live team sync · v{loadedVersion}</span></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{COVER_FIELDS.map(([key,label])=><div key={key} className="space-y-1"><Label className="text-xs text-muted-foreground">Editable label</Label><Input aria-label={`${label} label`} value={coverLabels[key]||label} onChange={e=>setCoverLabels(prev=>({...prev,[key]:e.target.value}))}/><Label className="text-xs text-muted-foreground">Value</Label><Input aria-label={`${label} value`} value={coverDetails[key]||''} onChange={e=>setCoverDetails(prev=>({...prev,[key]:e.target.value}))}/></div>)}</div><div className="mt-4"><Label>Additional cover fields</Label><p className="mb-2 text-xs text-muted-foreground">Optional manual fields, one per line in Label: Value format.</p><Textarea rows={3} value={additionalFieldsText} onChange={e=>setAdditionalFieldsText(e.target.value)} placeholder="Project Number: PRJ-001&#10;PMC: Example PMC"/></div></div>
   <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-lg border p-4"><Label>Customer cover/index file</Label><p className="mb-3 text-xs text-muted-foreground">PDF, PNG or JPEG. The system reads cover details and index order automatically; no existing package is required.</p><Input type="file" accept=".pdf,image/png,image/jpeg" disabled={analyze.isPending} onChange={uploadSource}/>{analyze.isPending&&<p className="mt-2 flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin"/>Reading customer document…</p>}</div>
   <div className="rounded-lg border p-4"><Label>Index &amp; automatic divider order</Label><p className="mb-3 text-xs text-muted-foreground">Paste one section per line, then drag rows to arrange the final index, dividers and all documents under them.</p><Textarea rows={5} value={indexText} onChange={e=>setIndexText(e.target.value)}/><div className="mt-3 space-y-2">{parseIndex(indexText).map((section,i)=><div key={section.id} draggable onDragStart={()=>setDragIndex(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragIndex!==null)moveSection(dragIndex,i);setDragIndex(null)}} className="flex items-center gap-2 rounded-md border bg-background p-2 shadow-sm"><GripVertical className="h-5 w-5 cursor-grab text-muted-foreground"/><span className="w-7 text-sm font-semibold text-primary">{i+1}</span><Input value={section.name} onChange={e=>updateSection(i,e.target.value)}/><Button type="button" size="icon" variant="ghost" onClick={()=>removeSection(i)} aria-label={`Remove ${section.name}`}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>)}</div><div className="mt-3 flex gap-2"><Input value={newSection} onChange={e=>setNewSection(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSection()}}} placeholder="Add Consultant Comment, Reply to Consultant Comment…"/><Button type="button" variant="outline" onClick={addSection}><Plus className="h-4 w-4"/>Add section</Button></div></div></div>
   <div className="rounded-lg border p-4"><div className="mb-3"><Label>Cover, index, divider &amp; brand design</Label><p className="text-xs text-muted-foreground">Choose reusable assets for this package. Upload new PDF templates or a PNG/JPEG logo below; all selections are saved with this workspace.</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{(['cover','index','divider','logo'] as const).map(type=><div key={type}><Label className="capitalize">{type} {type==='logo'?'image':'template'}</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={templateIds[type]} onChange={e=>setTemplateIds(prev=>({...prev,[type]:e.target.value}))}><option value="">KINAIR standard</option>{(templates.data??[]).filter((t:any)=>t.template_type===type).map((t:any)=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></div>)}</div></div>
   <div className="rounded-lg border border-primary/30 bg-primary/5 p-4"><Label>AI material-schedule model selection</Label><p className="mb-3 text-xs text-muted-foreground">Upload PDF, image, Excel or CSV. AI can select multiple exact database models and multiple series; unavailable lines are never substituted silently.</p><Input type="file" accept=".pdf,image/png,image/jpeg,.xlsx,.xls,.csv" disabled={analyzeSchedule.isPending} onChange={uploadSchedule}/>{analyzeSchedule.isPending&&<p className="mt-2 flex items-center gap-2 text-sm"><Loader2 className="h-4 w-4 animate-spin"/>Reading schedule and matching models…</p>}{scheduleResult&&<div className="mt-3 rounded-md border bg-background p-3 text-sm"><b>{scheduleResult.matched_model_ids?.length||0} model(s) selected across {(scheduleResult.matched_series??[]).join(', ')||'no matched series'}</b>{scheduleResult.summary&&<p className="text-muted-foreground">{scheduleResult.summary}</p>}{scheduleResult.unmatched?.length>0&&<div className="mt-2 text-amber-700"><b>Needs review:</b><ul className="list-disc pl-5">{scheduleResult.unmatched.map((line:string,i:number)=><li key={i}>{line}</li>)}</ul></div>}</div>}</div>
   <div className="rounded-lg border p-4"><Label>Required product series</Label><p className="mb-3 text-xs text-muted-foreground">Select one or multiple series. Catalogue, O&amp;M Manual, Test Certificate and Approval Copies mapped to these series will be attached automatically.</p><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{SERIES.map(s=><label key={s.name} className="flex items-center gap-2 rounded-md border p-2"><input type="checkbox" checked={chosenSeries.has(s.name)} onChange={()=>setChosenSeries(prev=>{const n=new Set(prev);n.has(s.name)?n.delete(s.name):n.add(s.name);return n})}/><span><b>{s.name}</b><small className="block text-muted-foreground">{s.brand} · {s.family}</small></span></label>)}</div></div>
   <div><Label>Products and models in this submittal</Label><div className="mt-2 grid gap-2 md:grid-cols-2">{(products.data??[]).flatMap((p:any)=>p.submittal_product_models.map((m:any)=><label key={m.id} className="flex items-center gap-3 rounded-md border p-3"><input type="checkbox" checked={selectedModels.has(m.id)} onChange={()=>toggle(m.id)}/><span><b>{m.code||m.name}</b><small className="block text-muted-foreground">{p.name} · {m.name}{modelMap.get(m.id)?.series?` · ${modelMap.get(m.id)?.series}`:''}</small></span></label>))}{!products.isLoading&&!(products.data??[]).some((p:any)=>p.submittal_product_models.length)&&<p className="text-sm text-muted-foreground">Add products and models in Product List first.</p>}</div></div>
   <div className="flex flex-wrap justify-end gap-2"><span className="mr-auto self-center text-xs text-muted-foreground">{saveWorkspace.isPending?'Saving changes…':packageId?'Autosave active':'Draft will be created when you upload or paste'}</span><Button variant="secondary" disabled={!packageId||saveWorkspace.isPending} onClick={()=>saveWorkspace.mutate()}>Save now</Button><Button variant="outline" disabled={!selectedPackage||revise.isPending} onClick={()=>revise.mutate()}><RotateCcw className="h-4 w-4"/>New revision</Button><Button variant="outline" disabled={!packageId||build.isPending} onClick={()=>build.mutate()}><FileSearch className="h-4 w-4"/>Validate & auto-build</Button><Button disabled={!packageId||!result||counts.missing>0||generate.isPending} onClick={()=>generate.mutate()}><UploadCloud className="h-4 w-4"/>Generate final submittal</Button></div>
  </CardContent></Card>
  {packageId&&<SubmittalAttachments packageId={packageId} sectionNames={parseIndex(indexText).map(x=>x.name)}/>}
  <SubmittalTemplates/>
  <Card><CardHeader><CardTitle>Live assembly &amp; preflight</CardTitle><CardDescription>{result?`${counts.ready} ready · ${counts.missing} missing · ${counts.warning} warnings. Dividers and documents follow this exact order.`:'Run Validate & auto-build to match default and project documents.'}</CardDescription></CardHeader><CardContent className="space-y-2">{parseIndex(indexText).map((section,i)=>{const r=(result??[]).find((x:any)=>x.section===section.name);return <div key={section.id} className="flex gap-3 rounded-md border p-3">{!r?<span className="flex h-5 w-5 items-center justify-center rounded-full bg-muted text-xs">{i+1}</span>:r.state==='ready'?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:r.state==='missing'?<XCircle className="h-5 w-5 text-destructive"/>:<AlertTriangle className="h-5 w-5 text-amber-600"/>}<div><b>{i+1}. {section.name}</b><p className="text-xs text-muted-foreground">{r?.documents?.length?r.documents.join(' · '):r?'No matching document. Upload a project file or map a library default.':'Awaiting validation'}</p></div></div>})}</CardContent></Card>
 </div>
}
