import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDown, ArrowUp, FileUp, Trash2 } from 'lucide-react';
import { supabase } from '@/integrations/backend/client';
import { useAuth } from '@/lib/authContext';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
const db=supabase as any;const bucket='submittal-control';
const defaults={regular:['Proposed Materials','Compliance Statement','Product Catalogues','Test Reports','Country of Origin','Draft Warranty Certificate','List of Previous Projects','Previous Approvals'],pq:['Scope of Works','Draft Warranty'],om:['Equipment Schedule','Operation Manuals','Installation Manuals','Commissioning Records','Maintenance Schedule','Spare Parts','Warranty Certificates','As-Built Drawings']};
export function SubmittalAttachments({packageId:controlledPackageId,sectionNames=[]}:{packageId?:string;sectionNames?:string[]}={}){
 const {user,tenantId}=useAuth();const {toast}=useToast();const qc=useQueryClient();const [localPackageId,setPackageId]=useState('');const packageId=controlledPackageId??localPackageId;const [custom,setCustom]=useState('');
 const packages=useQuery({queryKey:['submittal-packages',tenantId],enabled:!!tenantId,queryFn:async()=>{const {data,error}=await db.from('submittal_packages').select('id,project_name,package_type,reference,index_sections').eq('tenant_id',tenantId).order('created_at',{ascending:false});if(error)throw error;return data??[]}});
 const attachments=useQuery({queryKey:['submittal-attachments',packageId],enabled:!!packageId,queryFn:async()=>{const {data,error}=await db.from('submittal_attachments').select('*').eq('package_id',packageId).order('sort_order');if(error)throw error;return data??[]}});
 const selected=packages.data?.find((p:any)=>p.id===packageId);const sections=useMemo(()=>Array.from(new Set([...sectionNames,...((selected?.index_sections??[]) as any[]).map(x=>x.name).filter(Boolean),...(selected?defaults[selected.package_type as keyof typeof defaults]:[]),...((attachments.data??[]) as any[]).map(a=>a.section_name),...(custom?[custom]:[])])),[sectionNames,selected,attachments.data,custom]);
 const refresh=()=>qc.invalidateQueries({queryKey:['submittal-attachments',packageId]});
 const upload=useMutation({mutationFn:async(v:{file:File;section:string})=>{if(!tenantId||!user||!packageId)throw new Error('Select a package');const path=`${tenantId}/attachments/${packageId}/${crypto.randomUUID()}-${v.file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error:se}=await db.storage.from(bucket).upload(path,v.file,{contentType:'application/pdf'});if(se)throw se;const {error}=await db.from('submittal_attachments').insert({tenant_id:tenantId,package_id:packageId,section_name:v.section,display_name:v.file.name,storage_path:path,sort_order:(attachments.data??[]).length,created_by:user.id});if(error){await db.storage.from(bucket).remove([path]);throw error}},onSuccess:refresh});
 const reorder=useMutation({mutationFn:async(v:{id:string;order:number})=>{const {error}=await db.from('submittal_attachments').update({sort_order:v.order}).eq('id',v.id);if(error)throw error},onSuccess:refresh});
 const remove=useMutation({mutationFn:async(v:any)=>{const {error}=await db.from('submittal_attachments').delete().eq('id',v.id);if(error)throw error;await db.storage.from(bucket).remove([v.storage_path])},onSuccess:refresh});
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const file=f.get('file');if(!(file instanceof File)||!file.size)return;try{await upload.mutateAsync({file,section:String(f.get('section'))});(e.currentTarget as HTMLFormElement).reset();toast({title:'Attachment added'})}catch(x){toast({title:'Upload failed',description:x instanceof Error?x.message:'Retry',variant:'destructive'})}}
 const sectionRank=new Map(sections.map((name,i)=>[name,i]));const rows=[...((attachments.data??[]) as any[])].sort((a,b)=>(sectionRank.get(a.section_name)??999)-(sectionRank.get(b.section_name)??999)||a.sort_order-b.sort_order);
 function move(row:any,d:number){const group=rows.filter(x=>x.section_name===row.section_name);const i=group.findIndex(x=>x.id===row.id),j=i+d;if(j<0||j>=group.length)return;void Promise.all([reorder.mutateAsync({id:group[i].id,order:group[j].sort_order}),reorder.mutateAsync({id:group[j].id,order:group[i].sort_order})])}
 return <div className="space-y-5"><Card><CardHeader><CardTitle>Attachments & Divider Sections</CardTitle><CardDescription>Select a saved package, use a standard divider or add a custom one, then arrange PDF order.</CardDescription></CardHeader><CardContent className="space-y-4">{!controlledPackageId&&<div><Label>Package</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={packageId} onChange={e=>setPackageId(e.target.value)}><option value="">Select package</option>{packages.data?.map((p:any)=><option key={p.id} value={p.id}>{p.reference||'Draft'} · {p.project_name}</option>)}</select></div>}<div className="flex gap-2"><Input placeholder="Custom divider name" value={custom} onChange={e=>setCustom(e.target.value)}/><Button type="button" variant="outline" onClick={()=>setCustom(custom.trim())}>Add custom divider</Button></div><form onSubmit={submit} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select name="section" required className="h-10 rounded-md border bg-background px-3"><option value="">Divider section</option>{sections.map(s=><option key={s} value={s}>{s}</option>)}</select><Input name="file" type="file" accept="application/pdf" required/><Button disabled={!packageId||upload.isPending}><FileUp className="h-4 w-4"/>Add PDF</Button></form></CardContent></Card><div className="space-y-2">{rows.map(a=>{const group=rows.filter(x=>x.section_name===a.section_name),i=group.findIndex(x=>x.id===a.id);return <Card key={a.id}><CardContent className="flex items-center gap-3 p-3"><div className="min-w-0 flex-1"><b>{(sectionRank.get(a.section_name)??0)+1}. {a.section_name}</b><p className="truncate text-sm text-muted-foreground">{a.display_name}</p></div><Button variant="ghost" size="icon" disabled={i===0} onClick={()=>move(a,-1)}><ArrowUp className="h-4 w-4"/></Button><Button variant="ghost" size="icon" disabled={i===group.length-1} onClick={()=>move(a,1)}><ArrowDown className="h-4 w-4"/></Button><Button variant="ghost" size="icon" onClick={()=>remove.mutate(a)}><Trash2 className="h-4 w-4 text-destructive"/></Button></CardContent></Card>})}</div></div>
}