import { FormEvent, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileText, Trash2, Upload } from 'lucide-react';
import { supabase } from '@/integrations/backend/client';
import { useAuth } from '@/lib/authContext';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
const db=supabase as any;const BUCKET='submittal-control';const safe=(v:string)=>v.replace(/[^a-zA-Z0-9._-]+/g,'-');
const SERIES=['KVF-P','KVF-M','KVF-MR','KIN-E','KTAF','N-Cross Flow','N-Centrifugal Flow','XD-Centrifugal Flow','VVS','WING'];
const CATEGORIES=['Company Profile','Trade License','Certificates','Authorization Letter','Project Specification','Compliance Statement','List of Materials / BOQ','Product Catalogue','O&M Manual','Datasheet','Technical Drawing','Test Certificate','Approval Copies','Test Reports','Method Statement','Estidama Form','Warranty Certificate','Country of Origin','Previous Material Approvals / Project List'];
type Doc={id:string;category:string;display_name:string;storage_path:string;company_name:string|null;scope_type:string;package_id:string|null;series_name:string|null;expires_on:string|null;is_mandatory:boolean;submittal_products?:{name:string}|null;submittal_product_models?:{name:string;code:string|null}|null};
type Template={id:string;company_name:string;template_type:'cover'|'index'|'divider'|'logo'|'stamp';display_name:string;storage_path:string;field_map:Record<string,unknown>};

function useFiles(table:'submittal_documents'|'submittal_templates'){
 const {user,tenantId}=useAuth();const qc=useQueryClient();const key=[table,tenantId];
 const list=useQuery({queryKey:key,enabled:!!tenantId,queryFn:async()=>{const select=table==='submittal_documents'?'*,submittal_products(name),submittal_product_models(name,code)':'*';const {data,error}=await db.from(table).select(select).eq('tenant_id',tenantId).order('created_at',{ascending:false});if(error)throw error;return data??[]}});
 const upload=useMutation({mutationFn:async(v:{file:File;record:Record<string,unknown>})=>{if(!user||!tenantId)throw new Error('Sign in required');const path=`${tenantId}/${table}/${crypto.randomUUID()}-${safe(v.file.name)}`;const {error:storageError}=await db.storage.from(BUCKET).upload(path,v.file,{contentType:v.file.type,upsert:false});if(storageError)throw storageError;const {error}=await db.from(table).insert({tenant_id:tenantId,created_by:user.id,storage_path:path,...v.record});if(error){await db.storage.from(BUCKET).remove([path]);throw error}},onSuccess:()=>qc.invalidateQueries({queryKey:key})});
 const remove=useMutation({mutationFn:async(v:{id:string;path:string})=>{const {error}=await db.from(table).delete().eq('id',v.id);if(error)throw error;await db.storage.from(BUCKET).remove([v.path])},onSuccess:()=>qc.invalidateQueries({queryKey:key})});
 return {list,upload,remove};
}
export function SubmittalDocuments(){
 const f=useFiles('submittal_documents');const {toast}=useToast();const {tenantId}=useAuth();const [scope,setScope]=useState('company');const [productId,setProductId]=useState('');
 const packages=useQuery({queryKey:['document-packages',tenantId],enabled:!!tenantId,queryFn:async()=>{const {data,error}=await db.from('submittal_packages').select('id,reference,project_name').eq('tenant_id',tenantId).order('created_at',{ascending:false});if(error)throw error;return data??[]}});
 const products=useQuery({queryKey:['document-products',tenantId],enabled:!!tenantId,queryFn:async()=>{const {data,error}=await db.from('submittal_products').select('id,name,submittal_product_models(id,name,code)').eq('tenant_id',tenantId).order('name');if(error)throw error;return data??[]}});
 const models=useMemo(()=>products.data?.find((p:any)=>p.id===productId)?.submittal_product_models??[],[products.data,productId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const file=d.get('file');if(!(file instanceof File)||!file.size)return;try{await f.upload.mutateAsync({file,record:{display_name:String(d.get('display_name')||file.name),category:String(d.get('category')),company_name:String(d.get('company_name')||'')||null,scope_type:scope,product_id:['product','model'].includes(scope)?String(d.get('product_id')||'')||null:null,model_id:scope==='model'?String(d.get('model_id')||'')||null:null,series_name:scope==='series'?String(d.get('series_name')||'')||null:null,package_id:scope==='project'?String(d.get('package_id')||'')||null:null,keywords:String(d.get('keywords')||'').split(',').map(x=>x.trim()).filter(Boolean),is_mandatory:d.get('is_mandatory')==='on',expires_on:String(d.get('expires_on')||'')||null}});form.reset();setScope('company');setProductId('');toast({title:'Controlled document uploaded'})}catch(x){toast({title:'Upload failed',description:x instanceof Error?x.message:'Please retry',variant:'destructive'})}}
 return <div className="space-y-5"><Card><CardHeader><CardTitle>Controlled Document Library</CardTitle><CardDescription>Upload each Catalogue, O&amp;M Manual, Test Certificate and Approval Copy once at series level. The builder reuses the applicable files automatically for every package.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field name="display_name" label="Display name"/><div className="space-y-1"><Label>Index category</Label><select name="category" className="h-10 w-full rounded-md border bg-background px-3">{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></div><div className="space-y-1"><Label>Applies to</Label><select value={scope} onChange={e=>setScope(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="company">All KINAIR submittals</option><option value="product">Product</option><option value="series">Series</option><option value="model">Exact model</option><option value="project">Project-specific</option></select></div>
 {['product','model'].includes(scope)&&<div className="space-y-1"><Label>Product / series</Label><select name="product_id" required value={productId} onChange={e=>setProductId(e.target.value)} className="h-10 w-full rounded-md border bg-background px-3"><option value="">Select</option>{products.data?.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>}
 {scope==='model'&&<div className="space-y-1"><Label>Exact model</Label><select name="model_id" required className="h-10 w-full rounded-md border bg-background px-3"><option value="">Select</option>{models.map((m:any)=><option key={m.id} value={m.id}>{m.code||m.name}</option>)}</select></div>}
 {scope==='series'&&<div className="space-y-1"><Label>Brand / product series</Label><select name="series_name" required className="h-10 w-full rounded-md border bg-background px-3"><option value="">Select series</option><optgroup label="KINAIR Fans">{SERIES.slice(0,5).map(x=><option key={x}>{x}</option>)}</optgroup><optgroup label="KINAIR Air Curtains">{SERIES.slice(5,8).map(x=><option key={x}>{x}</option>)}</optgroup><optgroup label="VTS Clima">{SERIES.slice(8).map(x=><option key={x}>{x}</option>)}</optgroup></select></div>}{scope==='project'&&<div className="space-y-1"><Label>Project package</Label><select name="package_id" required className="h-10 w-full rounded-md border bg-background px-3"><option value="">Select package</option>{packages.data?.map((p:any)=><option key={p.id} value={p.id}>{p.reference||'Draft'} · {p.project_name}</option>)}</select></div>}<Field name="keywords" label="Matching keywords" placeholder="catalogue, product data, technical data"/><Field name="company_name" label="Company"/><Field name="expires_on" label="Expiry date" type="date"/><label className="flex items-end gap-2 pb-2"><input name="is_mandatory" type="checkbox"/>Mandatory when applicable</label><div className="space-y-1"><Label>PDF file</Label><Input name="file" type="file" accept="application/pdf" required/></div><Button disabled={f.upload.isPending} className="self-end"><Upload className="h-4 w-4"/>Upload & map</Button></form></CardContent></Card>
 <div className="grid gap-3">{((f.list.data??[]) as Doc[]).map(r=><Card key={r.id}><CardContent className="flex items-center justify-between gap-3 p-4"><div className="flex min-w-0 gap-3"><FileText className="h-5 w-5 shrink-0 text-primary"/><div className="min-w-0"><b>{r.display_name}</b><p className="text-xs text-muted-foreground">{r.category} · {r.scope_type}{r.submittal_products?.name?` · ${r.submittal_products.name}`:''}{r.submittal_product_models?` · ${r.submittal_product_models.code||r.submittal_product_models.name}`:''}{r.series_name?` · ${r.series_name}`:''}{r.is_mandatory?' · mandatory':''}{r.expires_on?` · expires ${r.expires_on}`:''}</p></div></div><Button variant="ghost" size="icon" aria-label={'Delete '+r.display_name} onClick={()=>f.remove.mutate({id:r.id,path:r.storage_path})}><Trash2 className="h-4 w-4 text-destructive"/></Button></CardContent></Card>)}{!f.list.isLoading&&!f.list.data?.length&&<div className="rounded-lg border border-dashed p-10 text-center text-muted-foreground">No controlled documents uploaded.</div>}</div></div>;
}
export function SubmittalTemplates(){
 const f=useFiles('submittal_templates');const {toast}=useToast();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const file=d.get('file');if(!(file instanceof File)||!file.size)return;let field_map={};try{field_map=JSON.parse(String(d.get('field_map')||'{}'))}catch{toast({title:'Invalid field-map JSON',variant:'destructive'});return}try{await f.upload.mutateAsync({file,record:{display_name:String(d.get('display_name')||file.name),company_name:String(d.get('company_name')),template_type:String(d.get('template_type')),field_map}});form.reset();toast({title:String(d.get('template_type'))==='stamp'?'Company stamp uploaded':'Template uploaded'})}catch(x){toast({title:'Upload failed',description:x instanceof Error?x.message:'Please retry',variant:'destructive'})}}
 return <FilePanel title="Templates & Company Stamps" description="Upload reusable cover, index and divider PDF backgrounds, plus brand logos and company stamps." onSubmit={submit} pending={f.upload.isPending} fields={<><Field name="display_name" label="Display name"/><Field name="company_name" label="Company" required/><div className="space-y-1"><Label>Type</Label><select name="template_type" className="h-10 w-full rounded-md border bg-background px-3"><option value="cover">Cover</option><option value="index">Index</option><option value="divider">Divider</option><option value="logo">Brand logo</option><option value="stamp">Company stamp</option></select></div><Field name="field_map" label="Field map JSON" defaultValue="{}"/></>} rows={(f.list.data??[]) as Template[]} remove={f.remove.mutate}/>;
}
function FilePanel({title,description,onSubmit,pending,fields,rows,remove}:{title:string;description:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;pending:boolean;fields:React.ReactNode;rows:any[];remove:(v:{id:string;path:string})=>void}){return <div className="space-y-5"><Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent><form onSubmit={onSubmit} className="grid gap-3 md:grid-cols-2">{fields}<div className="space-y-1"><Label>File</Label><Input name="file" type="file" accept=".pdf,image/png,image/jpeg" required/></div><Button disabled={pending} className="self-end"><Upload className="h-4 w-4"/>Upload</Button></form></CardContent></Card><div className="grid gap-3">{rows.map(r=><Card key={r.id}><CardContent className="flex items-center justify-between p-4"><div className="flex gap-3"><FileText className="h-5 w-5 text-primary"/><div><b>{r.display_name}</b><p className="text-xs text-muted-foreground">{r.category||r.template_type}{r.company_name?` · ${r.company_name}`:''}</p></div></div><Button variant="ghost" size="icon" aria-label={'Delete '+r.display_name} onClick={()=>remove({id:r.id,path:r.storage_path})}><Trash2 className="h-4 w-4 text-destructive"/></Button></CardContent></Card>)}{rows.length===0&&<div className="rounded-lg border border-dashed p-10 text-center text-muted-foreground">No files uploaded.</div>}</div></div>}
function Field({label,...p}:React.ComponentProps<typeof Input>&{label:string}){return <div className="space-y-1"><Label>{label}</Label><Input {...p}/></div>}
