import { useEffect, useRef, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { supabase as client } from '@/integrations/backend/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { summarizeUsage, type UsageEvent, type UsageRate } from '@/lib/submittal-lite/advanced';
const db=client as unknown as SupabaseClient;
export function AiUsageDashboard({tenantId}:{tenantId:string}){
 const [open,setOpen]=useState(false),[days,setDays]=useState(7),[events,setEvents]=useState<UsageEvent[]>([]),[rates,setRates]=useState<UsageRate[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false),[capped,setCapped]=useState(false);
 const [rateKey,setRateKey]=useState(''),[input,setInput]=useState(''),[output,setOutput]=useState('');
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn();}catch(e){if(alive.current)setNotice(e instanceof Error?e.message:'Could not load usage.');}finally{if(alive.current)setBusy(false);}};
 const refresh=()=>void run(async()=>{const until=new Date().toISOString(),since=new Date(Date.now()-days*86400000).toISOString();const all:UsageEvent[]=[];let more=false;for(let offset=0;offset<10000;offset+=1000){const {data,error}=await db.from('submittal_ai_usage').select('id,created_at,request_id,action,provider,model,outcome,input_tokens,output_tokens,latency_ms').eq('tenant_id',tenantId).gte('created_at',since).lte('created_at',until).order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+999);if(error)throw error;all.push(...(data||[]));if((data||[]).length<1000)break;if(offset===9000)more=true;}
 const {data,error}=await db.from('submittal_ai_rates').select('provider,model,input_usd,output_usd').eq('tenant_id',tenantId);if(error)throw error;if(alive.current){setEvents(all);setRates(data||[]);setCapped(more);setLoaded(true);}});
 const groups=summarizeUsage(events,rates);const estimate=groups.reduce((s,g)=>s+g.estimate,0),unknown=groups.reduce((s,g)=>s+g.unknown+g.unpriced,0);
 return <section className="mx-5 mb-4 rounded-2xl border bg-card p-4 lg:mx-8"><Button variant="outline" onClick={()=>{setOpen(!open);if(!open)refresh();}}>AI usage & estimated cost</Button>{open&&<div className="mt-4 space-y-4"><p className="text-sm text-muted-foreground">Server submittal-assistant attempts recorded from this release onward. Includes document reading and fallback attempts. Browser-local work and separate selection engines are not tracked. Generated means a model returned a response, not that technical checks passed.</p><div className="flex flex-wrap gap-2"><select aria-label="Usage date range" className="rounded border bg-background p-2" value={days} disabled={busy} onChange={e=>{setDays(Number(e.target.value));setLoaded(false);}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select><Button disabled={busy} onClick={refresh}>{busy?'Loading…':'Refresh usage'}</Button></div>
 {loaded&&<><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-muted p-3"><strong>{events.length}</strong><p className="text-xs">Recorded attempts · {new Set(events.map(e=>e.request_id)).size} requests</p></div><div className="rounded-xl bg-muted p-3"><strong>${estimate.toFixed(4)}</strong><p className="text-xs">Estimate at configured rates</p></div><div className="rounded-xl bg-muted p-3"><strong>{unknown}</strong><p className="text-xs">Attempts excluded from estimate: unknown tokens or rate</p></div></div>{capped&&<p className="text-sm text-amber-700">Showing only the latest 10,000 attempts. Totals are partial.</p>}<div className="overflow-auto"><table className="w-full text-xs"><thead><tr>{['Model / provider','Attempts / errors','Input / output tokens','Unknown / unpriced','Estimated USD'].map(h=><th key={h} className="border p-2 text-left">{h}</th>)}</tr></thead><tbody>{groups.map(g=><tr key={`${g.provider}:${g.model}`}><td className="border p-2">{g.model}<br/>{g.provider}</td><td className="border p-2">{g.calls} / {g.failed}</td><td className="border p-2">{g.input.toLocaleString()} / {g.output.toLocaleString()}</td><td className="border p-2">{g.unknown} / {g.unpriced}</td><td className="border p-2">${g.estimate.toFixed(4)}</td></tr>)}</tbody></table></div>{!events.length&&<p className="text-sm">No attempts recorded in this period yet.</p>}</>}
 <details><summary className="cursor-pointer text-sm font-semibold">Configure estimate rates</summary><p className="my-2 text-xs">Enter your provider's USD rate per million input/output tokens. These rates recalculate the displayed estimate; they are not invoice totals. Cached-token discounts, provider fees and taxes are not included.</p><select className="w-full rounded border bg-background p-2 text-sm" aria-label="Model to price" value={rateKey} onChange={e=>{setRateKey(e.target.value);const g=groups.find(g=>JSON.stringify([g.provider,g.model])===e.target.value),r=rates.find(r=>g&&r.provider===g.provider&&r.model===g.model);setInput(r?String(r.input_usd):'');setOutput(r?String(r.output_usd):'');}}><option value="">Choose a recorded model</option>{groups.map(g=><option key={`${g.provider}:${g.model}`} value={JSON.stringify([g.provider,g.model])}>{g.provider} · {g.model}</option>)}</select><div className="my-2 grid gap-2 sm:grid-cols-2"><label className="text-xs">Input USD / 1M tokens<Input type="number" min="0" step="any" value={input} onChange={e=>setInput(e.target.value)}/></label><label className="text-xs">Output USD / 1M tokens<Input type="number" min="0" step="any" value={output} onChange={e=>setOutput(e.target.value)}/></label></div><Button disabled={busy||!rateKey||input===''||output===''} onClick={()=>void run(async()=>{const [provider,model]=JSON.parse(rateKey);const a=Number(input),b=Number(output);if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<0||a>=1000000||b>=1000000)throw new Error('Enter valid nonnegative rates.');const r={provider,model,input_usd:a,output_usd:b};const {error}=await db.from('submittal_ai_rates').upsert({tenant_id:tenantId,...r});if(error)throw error;if(alive.current){setRates(old=>[...old.filter(x=>x.provider!==provider||x.model!==model),r]);setNotice('Estimate rates saved.');}})}>Save rates</Button></details>
 {loaded&&!!events.length&&<details><summary className="cursor-pointer text-sm">Latest 50 attempts</summary><div className="max-h-72 overflow-auto text-xs">{events.slice(0,50).map(e=><p key={e.id} className="border-b py-2">{new Date(e.created_at).toLocaleString()} · {e.action} · {e.model} · {e.outcome} · {(e.latency_ms/1000).toFixed(1)}s · request {e.request_id.slice(0,8)}</p>)}</div></details>}
 {notice&&<p role="status" className="text-sm">{notice}</p>}</div>}</section>;
}
