import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {uploadSubmittalFile} from '@/lib/submittal-lite/idb';
import type {DocRef} from '@/lib/submittal-lite/records';
export function RtccSupportingDocuments({comment,ids,docs,onChange,onAttach,onBusy}:{comment:string;ids:string[];docs:DocRef[];onChange:(ids:string[])=>void;onAttach:(doc:DocRef)=>void;onBusy:(b:boolean)=>void}){
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const move=(at:number,direction:number)=>{const copy=[...ids],next=at+direction;if(next<0||next>=copy.length)return;[copy[at],copy[next]]=[copy[next],copy[at]];onChange(copy);};
 return <div className="mt-3 rounded border p-3 space-y-2"><strong className="block text-sm">Supporting documents — comment {comment}</strong><p className="text-xs">Multiple PDF, PNG or JPG files. Printed after RTCC, in comment order and the file order below. Use ↑ / ↓ to change the upload order.</p>
 <input aria-label={`Upload supporting files for comment ${comment}`} className="min-h-11 max-w-full text-xs" type="file" multiple accept=".pdf,.png,.jpg,.jpeg" disabled={busy} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;if(files.some(f=>! /\.(pdf|png|jpe?g)$/i.test(f.name))){setNotice('Choose PDF, PNG or JPG files.');return;}setBusy(true);onBusy(true);const uploaded:DocRef[]=[];try{for(const file of files){setNotice(`Uploading ${uploaded.length+1} of ${files.length}: ${file.name}`);const id=crypto.randomUUID(),type=/\.pdf$/i.test(file.name)?'application/pdf':/\.png$/i.test(file.name)?'image/png':'image/jpeg';await uploadSubmittalFile(`doc:${id}`,new File([file],file.name,{type}));uploaded.push({id,name:file.name,type,size:file.size});}setNotice(`${uploaded.length} files attached in upload order. Review and save the document.`);}catch(e){setNotice(`${uploaded.length} files attached. ${e instanceof Error?e.message:'Upload failed.'} Retry remaining files.`);}finally{for(const file of uploaded)onAttach(file);if(uploaded.length)onChange([...ids,...uploaded.map(f=>f.id)]);setBusy(false);onBusy(false);}}}/>
 <ol className="space-y-2">{ids.map((id,i)=><li key={id} className="flex flex-wrap items-center gap-1 text-xs"><span className="min-w-0 flex-1 break-words">{i+1}. {docs.find(d=>d.id===id)?.name||'Missing file — reattach'}</span><Button variant="outline" size="sm" disabled={busy||i===0} aria-label={`Move attachment ${i+1} up for comment ${comment}`} onClick={()=>move(i,-1)}>↑</Button><Button variant="outline" size="sm" disabled={busy||i===ids.length-1} aria-label={`Move attachment ${i+1} down for comment ${comment}`} onClick={()=>move(i,1)}>↓</Button><Button variant="ghost" size="sm" disabled={busy} onClick={()=>onChange(ids.filter(x=>x!==id))}>Unlink</Button></li>)}</ol>
 <select aria-label={`Link existing file to comment ${comment}`} className="min-h-11 w-full rounded border bg-background p-2 text-xs" value="" disabled={busy} onChange={e=>{if(e.target.value)onChange([...ids,e.target.value]);}}><option value="">Link an existing uploaded file</option>{docs.filter(d=>!ids.includes(d.id)).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>
 {notice&&<p role="status" className="text-xs">{notice}</p>}
 </div>;
}
