import {appendRtccAttachments} from '@/lib/submittal-lite/rtcc-attachments';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {ComplianceEditor} from './ComplianceEditor';
import {RtccEditor} from './RtccEditor';
import {buildCompliancePdf} from '@/lib/submittal-lite/compliance-pdf';
import {buildReviewPdf} from '@/lib/submittal-lite/review-pdf';
import {rtccExportTables} from '@/lib/submittal-lite/review-excel';
import {uploadSubmittalFile} from '@/lib/submittal-lite/idb';
import {loadCloudRecords,putCloudRecord} from '@/lib/submittal-lite/cloud';
import {loadReplyDocuments,saveReplyDocument,newReplyDocument,replyDocumentReady,searchReplyTargets,mergeReplyDocument,type ReplyDocumentKind,type ReplyDocument,type SavedReplyDocument} from '@/lib/submittal-lite/reply-documents';
import type {DocRef,SubmittalRecord} from '@/lib/submittal-lite/records';
type Props={suggestedTargetId?:string;tenantId:string;kind:ReplyDocumentKind;companies:{id:string;name:string;logo?:string;stamp?:string}[];brands:{id:string;name:string;logo?:string;series:{id:string;name:string}[]}[];records:SubmittalRecord[];bytesOf:(id:string)=>Promise<ArrayBuffer|undefined>;onMerged:(record:SubmittalRecord)=>void;onOpenSubmittal:(record:SubmittalRecord)=>void};
export function StandaloneReplyBuilder({tenantId,kind,companies,brands,records,bytesOf,onMerged,onOpenSubmittal,suggestedTargetId}:Props){
 const [doc,setDoc]=useState<ReplyDocument>(()=>newReplyDocument(kind)),[saved,setSaved]=useState<SavedReplyDocument[]>([]),[version,setVersion]=useState<number>(),[snapshot,setSnapshot]=useState('');
 const [busy,setBusy]=useState(false),[editorBusy,setEditorBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[targetId,setTargetId]=useState(''),[replace,setReplace]=useState(false),[file,setFile]=useState<File>(),[merged,setMerged]=useState<SubmittalRecord>();
 useEffect(()=>{if(suggestedTargetId)setTargetId(current=>current||suggestedTargetId);},[suggestedTargetId]);
 const lock=useRef(false);const dirty=JSON.stringify(doc)!==snapshot;const disabled=busy||editorBusy;
 const recoveryKey=`reply-document:${tenantId}:${kind}`;
 const [recovery,setRecovery]=useState< {doc:ReplyDocument;version?:number}|null>(null),[recoveryProtected,setRecoveryProtected]=useState(true);
 useEffect(()=>{let live=true;loadReplyDocuments(tenantId).then(rows=>{if(live)setSaved(rows.filter(r=>r.kind===kind));}).catch(e=>{if(live)setNotice(e.message);});try{const raw=localStorage.getItem(recoveryKey);if(raw)setRecovery(JSON.parse(raw));}catch{/* Existing cloud documents remain available. */}return()=>{live=false;};},[tenantId,kind]);
 useEffect(()=>{if(!doc.compliance&&!doc.rtcc.length&&!doc.sections.length){setRecoveryProtected(true);return;}setRecoveryProtected(false);const timer=setTimeout(()=>{try{localStorage.setItem(recoveryKey,JSON.stringify({doc,version}));setRecoveryProtected(true);}catch{setRecoveryProtected(false);setNotice('Browser recovery storage is full. Use Save document to retain your work.');}},400);return()=>clearTimeout(timer);},[doc,version,recoveryKey]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty&&!recoveryProtected&&(doc.compliance||doc.rtcc.length||doc.sections.length)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,recoveryProtected,doc]);
 const run=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'Please retry.');}finally{lock.current=false;setBusy(false);}};
 const canReplace=()=>!dirty||(!doc.compliance&&!doc.rtcc.length&&!doc.sections.length)||window.confirm('You have unsaved document changes. Discard them and open another document?');
 const open=(next:ReplyDocument,v?:number)=>{if(!canReplace())return;setDoc(structuredClone(next));setVersion(v);setSnapshot(JSON.stringify(next));setMerged(undefined);setReplace(false);setNotice('Document opened. Changes here do not change a submittal until you merge.');};
 const save=async()=>{const result=await saveReplyDocument(tenantId,doc,version);setVersion(result.version);setSnapshot(JSON.stringify(doc));setSaved(rows=>[result,...rows.filter(r=>r.id!==result.id)]);setNotice('Document saved independently of submittals.');};
 const attach=(sectionId:string,ref:DocRef)=>setDoc(current=>{const target=current.sections.find(s=>s.id===sectionId&&!s.auto)||current.sections.find(s=>s.title==='SUPPORTING DOCUMENTS'&&!s.auto);return {...current,sections:target?current.sections.map(s=>s.id===target.id?{...s,docs:[...s.docs,ref]}:s):[...current.sections,{id:crypto.randomUUID(),title:'SUPPORTING DOCUMENTS',docs:[ref],stamp:'none'}]};});
 const target=records.find(r=>r.id===targetId);const matches=searchReplyTargets(records,query);const currentCompany=companies.find(c=>c.id===doc.scope.companyId);const currentBrand=brands.find(b=>b.id===doc.scope.brandId);const branding={companyLogo:currentCompany?.logo,brandLogo:currentBrand?.logo,stamp:currentCompany?.stamp};
 const documentPdf=async()=>{if(!doc.scope.companyId||!doc.scope.brandId)throw new Error('Select the company and brand for PDF branding first.');if(!replyDocumentReady(doc))throw new Error('Review the source and all replies first. Draft PDF/Excel previews are available below.');return doc.kind==='compliance'?buildCompliancePdf(doc.compliance!,doc.fields,Object.fromEntries(doc.sections.flatMap(s=>s.docs).map(d=>[d.id,d.name])),branding):appendRtccAttachments(await buildReviewPdf(rtccExportTables(doc.rtcc,doc.fields,doc.sections),branding),doc.rtcc,async id=>{const ref=doc.sections.flatMap(s=>s.docs).find(d=>d.id===id),bytes=await bytesOf(id);return ref&&bytes?{id,bytes,type:ref.type,name:ref.name}:undefined;});};
 const merge=()=>void run(async()=>{
  if(!target)throw new Error('Choose a submittal first.');
  const latest=await loadCloudRecords(tenantId),current=latest.find(r=>r.id===target.id);
  if(!current||current.updatedAt!==target.updatedAt)throw new Error('The target submittal changed. Refresh Submittal Control, reopen your saved document and select the latest revision.');
  // Validate before uploading files; the real PDF reference replaces this placeholder below.
  mergeReplyDocument(doc,current,latest,kind==='compliance'?{id:'validation',name:'Compliance.pdf',type:'application/pdf'}:undefined,replace);
  let pdf:DocRef|undefined;
  if(kind==='compliance'){const bytes=await documentPdf(),id=crypto.randomUUID();const f=new File([new Uint8Array(bytes)],'Compliance-Statement.pdf',{type:'application/pdf'});await uploadSubmittalFile(`doc:${id}`,f);pdf={id,name:f.name,type:f.type,size:f.size};}
  await save();const next=mergeReplyDocument(doc,current,latest,pdf,replace);await putCloudRecord(tenantId,next,next.id===current.id?current.updatedAt:undefined);onMerged(next);setMerged(next);setNotice(`Merged into ${next.ref} · Rev ${next.rev}. ${current.issuedPdf?'A new draft revision was created.':'Draft updated.'} Open the submittal to build and check its combined PDF.`);
 });
 const copyTarget=()=>{if(!target||!canReplace())return;const next:ReplyDocument={...newReplyDocument(kind),title:`${kind==='compliance'?'Compliance':'RTCC'} — ${target.ref}`,originRef:target.ref,scope:{companyId:target.companyId,brandId:target.brandId,seriesIds:[...target.seriesIds],customProducts:[...(target.customProducts||[])]},fields:structuredClone(target.fields),sections:structuredClone(target.sections.filter(s=>!s.auto).map(s=>({...s,docs:s.docs.filter(d=>d.id!==target.compliance?.generatedDocId)}))),compliance:kind==='compliance'&&target.compliance?{...structuredClone(target.compliance),generatedDocId:undefined}:undefined,rtcc:kind==='rtcc'?structuredClone(target.rtcc||[]):[]};setDoc(next);setVersion(undefined);setSnapshot('');setMerged(undefined);setNotice('Project setup, supporting files and existing replies copied into an independent document. The submittal is unchanged.');};
 return <section className="mx-3 space-y-4 pb-8 sm:mx-5 lg:mx-8">
  <div className="rounded-xl border bg-card p-4 space-y-3"><h2 className="text-xl font-bold">{kind==='compliance'?'Compliance Statement Builder':'RTCC Builder'}</h2><p className="text-sm">Create, save and export independently. Link to a submittal only when you need to merge.</p>
  <div className="flex flex-wrap gap-2"><Button disabled={disabled} onClick={()=>open(newReplyDocument(kind))}>New {kind==='compliance'?'compliance statement':'RTCC'}</Button><Button disabled={disabled} onClick={()=>void run(save)}>Save document</Button><span className="self-center text-sm">{busy?'Working…':dirty?'Unsaved changes':'Saved'}</span></div>
  <label className="block text-sm">Saved documents<select className="ml-2 min-h-11 max-w-full rounded border bg-background p-2" value={version?doc.id:''} disabled={disabled} onChange={e=>{const row=saved.find(r=>r.id===e.target.value);if(row)open(row.data,row.version);}}><option value="">Choose saved document</option>{saved.map(row=><option key={row.id} value={row.id}>{row.title} · {new Date(row.updated_at).toLocaleDateString()}</option>)}</select></label>
  {recovery&&<Button variant="outline" disabled={disabled} onClick={()=>{open(recovery.doc,recovery.version);setSnapshot('');setRecovery(null);}}>Recover last local draft</Button>}
  {notice&&<p role="status" className="rounded border p-3 text-sm">{notice}</p>}
  </div>
  <fieldset disabled={disabled} className="min-w-0 space-y-4">
   <div className="rounded-xl border border-primary/30 bg-card p-4 space-y-3">
    <div><h3 className="font-semibold">Company & brand for PDF</h3><p className="text-xs text-muted-foreground">Required for Compliance/RTCC PDF branding. Company logo appears at the left, brand logo at the right, and the selected company stamp is applied to every generated page.</p></div>
    <div className="grid gap-3 sm:grid-cols-2">
     <label className="text-sm font-medium">Company<select className="mt-1 block min-h-11 w-full rounded border bg-background p-2" value={doc.scope.companyId} onChange={e=>{const value=e.target.value;setDoc({...doc,scope:{...doc.scope,companyId:value},fields:doc.fields.map(f=>/^Supplier Name$/i.test(f.label)?{...f,value:companies.find(c=>c.id===value)?.name||''}:f)});}}><option value="">Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
     <label className="text-sm font-medium">Brand<select className="mt-1 block min-h-11 w-full rounded border bg-background p-2" value={doc.scope.brandId} onChange={e=>{const value=e.target.value;setDoc({...doc,scope:{...doc.scope,brandId:value,seriesIds:[]},fields:doc.fields.map(f=>/^Brand Name$/i.test(f.label)?{...f,value:brands.find(b=>b.id===value)?.name||''}:f)});}}><option value="">Select brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
    </div>
    {(!doc.scope.companyId||!doc.scope.brandId)&&<p className="text-sm text-amber-700">Select both company and brand before previewing, downloading or merging the PDF.</p>}
    {doc.scope.companyId&&doc.scope.brandId&&<p className="text-xs text-muted-foreground">PDF assets: Company logo {currentCompany?.logo?'✓':'missing'} · Brand logo {currentBrand?.logo?'✓':'missing'} · Company stamp {currentCompany?.stamp?'✓':'missing'}. Missing assets can be uploaded in Companies & Brands.</p>}
   </div>
   <details className="rounded-xl border bg-card">
    <summary className="cursor-pointer select-none p-4 font-semibold">Document & project details</summary>
    <div className="border-t p-4 space-y-3"><Input aria-label="Document title" value={doc.title} onChange={e=>setDoc({...doc,title:e.target.value})}/>
   {!!currentBrand?.series.length&&<details><summary className="cursor-pointer py-2">Proposed product series</summary><div className="flex flex-wrap gap-3">{currentBrand.series.map(s=><label key={s.id} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={doc.scope.seriesIds.includes(s.id)} onChange={e=>setDoc({...doc,scope:{...doc.scope,seriesIds:e.target.checked?[...doc.scope.seriesIds,s.id]:doc.scope.seriesIds.filter(id=>id!==s.id)}})}/>{s.name}</label>)}</div></details>}
   <label className="block text-sm">Other proposed products / models<Input value={(doc.scope.customProducts||[]).join(', ')} onChange={e=>setDoc({...doc,scope:{...doc.scope,customProducts:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}})}/></label>
   <div className="grid gap-3 sm:grid-cols-2">{doc.fields.map((f,i)=><label key={i} className="text-sm">{f.label}<Input value={f.value} onChange={e=>setDoc({...doc,fields:doc.fields.map((v,n)=>n===i?{...v,value:e.target.value}:v)})}/></label>)}</div>
    </div>
   </details>
  </fieldset>
  <fieldset disabled={busy} className="min-w-0">
  {kind==='compliance'?<ComplianceEditor standalone key={doc.id} branding={branding} brandingReady={!!doc.scope.companyId&&!!doc.scope.brandId} tenantId={tenantId} scope={doc.scope} fields={doc.fields} sections={doc.sections} sheet={doc.compliance} bytesOf={bytesOf} onBusy={setEditorBusy} onSupportAttach={attach} onChange={sheet=>setDoc(d=>({...d,compliance:{...sheet,generatedDocId:undefined},sections:d.sections.map(s=>({...s,docs:s.docs.filter(f=>f.id!==d.compliance?.generatedDocId)}))}))} onAttach={ref=>{attach('new',ref);setDoc(d=>({...d,compliance:d.compliance?{...d.compliance,generatedDocId:ref.id}:undefined}));}}/>:<RtccEditor standalone key={doc.id} branding={branding} brandingReady={!!doc.scope.companyId&&!!doc.scope.brandId} tenantId={tenantId} scope={doc.scope} contextKey={JSON.stringify({fields:doc.fields,scope:doc.scope,sections:doc.sections})} rounds={doc.rtcc} onChange={rounds=>setDoc(d=>({...d,rtcc:rounds}))} fields={doc.fields} sections={doc.sections} bytesOf={bytesOf} onBusy={setEditorBusy} onSupportAttach={attach}/>}
  </fieldset>
  {kind==='rtcc'&&<fieldset disabled={disabled} className="rounded-xl border p-4 space-y-3"><legend className="font-semibold">Uploaded RTCC files — link and order them under each comment</legend>{doc.sections.filter(s=>!s.auto).flatMap(s=>s.docs.map(d=><div key={s.id+d.id} className="flex items-center justify-between gap-2 text-sm"><span>{d.name} · {s.title}</span><Button variant="outline" onClick={()=>setDoc(current=>({...current,sections:current.sections.map(section=>section.id===s.id?{...section,docs:section.docs.filter(f=>f.id!==d.id)}:section)}))}>Remove</Button></div>))}</fieldset>}
  <fieldset disabled={disabled} className="rounded-xl border bg-card p-4 space-y-3"><legend className="font-semibold">Find a submittal & merge</legend><Input aria-label="Search submittal reference or file name" placeholder="Submittal reference, project, title or attached file name" value={query} onChange={e=>setQuery(e.target.value)}/>
  <select aria-label="Target submittal" className="min-h-11 w-full rounded border bg-background p-2" value={targetId} onChange={e=>{setTargetId(e.target.value);setReplace(false);setMerged(undefined);}}><option value="">Select a submittal</option>{[...new Map([...(target?[target]:[]),...matches].map(r=>[r.id,r])).values()].map(r=><option key={r.id} value={r.id}>{r.ref} · Rev {r.rev} · {r.project} · {r.title}</option>)}</select>
  {!matches.length&&<p className="text-sm">No matching submittal. You can still save and export this document independently.</p>}
  {target&&<><p className="text-sm">Selected: {target.ref} · Rev {target.rev}. {target.issuedPdf?'Merging creates a new draft revision.':'Merging updates this saved draft.'}</p><Button variant="outline" onClick={copyTarget}>Copy project setup & existing replies into a new document</Button>{kind==='compliance'&&target.compliance&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>Replace this submittal’s existing compliance statement</label>}<p className="text-xs">Original project fields and other documents stay in the target. New RTCC rounds receive the next available numbers. Rounds copied from this same reference replace their matching rounds.</p><Button disabled={!replyDocumentReady(doc)} onClick={merge}>Merge reviewed document into {target.ref}</Button></>}
  {merged&&<Button variant="outline" onClick={()=>onOpenSubmittal(merged)}>Open merged submittal</Button>}
  <details><summary className="cursor-pointer py-2 font-semibold">Or merge with a PDF file from your computer</summary><p className="text-sm">Appends the reviewed reply document to your selected PDF. RTCC supporting files follow the replies in comment and upload order. Downloads a combined copy; the original file is unchanged.</p><input aria-label="Submittal PDF to merge" className="my-3 max-w-full" type="file" accept=".pdf" onChange={e=>setFile(e.target.files?.[0])}/><Button disabled={!file||!replyDocumentReady(doc)} onClick={()=>void run(async()=>{if(!file)return;const {PDFDocument}=await import('pdf-lib');const output=await PDFDocument.load(await file.arrayBuffer());const reply=await PDFDocument.load(await documentPdf());for(const page of await output.copyPages(reply,reply.getPageIndices()))output.addPage(page);const url=URL.createObjectURL(new Blob([new Uint8Array(await output.save())],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='Submittal-with-'+kind+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setNotice('Combined PDF downloaded. Original PDF remains unchanged.');})}>Download merged PDF</Button></details>
  </fieldset>
 </section>;
}
