import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {supabase as client} from '@/integrations/backend/client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {workflowAction,packageLink,reviewIsStale} from '@/lib/submittal-lite/workflow';
import type {SubmittalRecord} from '@/lib/submittal-lite/records';
const db=client as unknown as SupabaseClient;
type Member={user_id:string;display_name:string;email:string};
type Review={snapshot:Record<string,unknown>;record_id:string;engineer_id:string;reviewer_id:string;due_date:string|null;status:string;updated_at:string;history:{event:string;at:string;by:string;note?:string}[]};
type Job={id:string;title:string;created_by:string;status:string;progress:number;page_count?:number;updated_at:string;error?:string;sources:{ref:string;rev:number}[]};
export function TeamWorkflow({tenantId,records,onEdit}:{tenantId:string;records:SubmittalRecord[];onEdit:(record:SubmittalRecord)=>void}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [members,setMembers]=useState<Member[]>([]),[userId,setUserId]=useState(''),[reviews,setReviews]=useState<Review[]>([]),[jobs,setJobs]=useState<Job[]>([]);
 const [recordId,setRecordId]=useState(''),[engineer,setEngineer]=useState(''),[reviewer,setReviewer]=useState(''),[due,setDue]=useState(''),[note,setNote]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[title,setTitle]=useState(''),[recipient,setRecipient]=useState(''),[purpose,setPurpose]=useState('For consultant review'),[links,setLinks]=useState<Record<string,string>>({});
 const refresh=async()=>{const [a,b]=await Promise.all([db.from('submittal_internal_reviews').select('*').eq('tenant_id',tenantId).order('updated_at',{ascending:false}).limit(500),db.from('submittal_package_jobs').select('id,title,created_by,status,progress,page_count,updated_at,error,sources').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(100)]);if(a.error||b.error)throw a.error||b.error;setReviews(a.data||[]);setJobs(b.data||[]);};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Request failed. Please retry.');}finally{setBusy(false);}};
 useEffect(()=>{if(!open)return;let stopped=false;const timer=window.setInterval(()=>{if(!stopped)void refresh().catch(()=>{});},10000);return()=>{stopped=true;window.clearInterval(timer);};},[open,tenantId]);
 const name=(id:string)=>members.find(m=>m.user_id===id)?.display_name||members.find(m=>m.user_id===id)?.email||'Workspace member';
 const chosen=records.find(r=>r.id===recordId);const review=reviews.find(r=>r.record_id===recordId);
 const issued=records.filter(r=>!!r.issuedPdf);const project=records.find(r=>selected.includes(r.id))?.project.trim().toLowerCase();
 return <section className="mx-5 mb-4 rounded-2xl border bg-card p-4 lg:mx-8"><Button variant="outline" onClick={()=>{setOpen(!open);if(!open)void run(async()=>{const data=await workflowAction<{members:Member[];userId:string}>({action:'members'});setMembers(data.members);setUserId(data.userId);setEngineer(data.userId);});}}>Team review & multi-brand packages</Button>
 {open&&<div className="mt-4 space-y-5"><p className="text-sm text-muted-foreground">Assign saved drafts for internal checking, then combine issued submittals for the same project. Internal approval is separate from consultant approval.</p>
 <div className="rounded-xl border p-4 space-y-3"><h2 className="font-semibold">Engineer assignment & internal review</h2><p className="text-xs text-muted-foreground">Save your editor changes first. Approval covers that saved content; later changes require another review. Requesting a review blocks final download, sharing and issue until approved.</p>
 <select aria-label="Submittal for internal review" className="w-full rounded border bg-background p-2" value={recordId} onChange={e=>{setRecordId(e.target.value);setNote('');const r=reviews.find(x=>x.record_id===e.target.value);setEngineer(r?.engineer_id||userId);setReviewer(r?.reviewer_id||'');setDue(r?.due_date||'');}}><option value="">Choose saved submittal</option>{records.map(r=><option key={r.id} value={r.id}>{r.ref} R{r.rev} · {r.project||r.title}</option>)}</select>
 {chosen&&<><Button variant="outline" size="sm" onClick={()=>onEdit(chosen)}>Open saved submittal</Button>{review&&<div className="rounded bg-muted p-3 text-sm"><p>Review: {chosen && reviewIsStale(review.snapshot,chosen)?'Outdated — saved content changed':review.status.replaceAll('_',' ')} · Engineer: {name(review.engineer_id)} · Reviewer: {name(review.reviewer_id)}</p><p>Due: {review.due_date||'Not set'}{review.status==='pending'&&review.due_date&&review.due_date<new Date().toISOString().slice(0,10)?' · Overdue':''}</p><details className="mt-2"><summary>Review history</summary>{review.history.map((h,i)=><p key={i} className="mt-2 text-xs">{new Date(h.at).toLocaleString()} · {name(h.by)} · {h.event.replaceAll('_',' ')}{h.note?` — ${h.note}`:''}</p>)}</details></div>}
 {!chosen.issuedPdf&&<><div className="grid gap-2 sm:grid-cols-3"><label className="text-xs">Application engineer<select aria-label="Assigned application engineer" value={engineer} onChange={e=>setEngineer(e.target.value)} className="mt-1 w-full rounded border bg-background p-2">{members.map(m=><option value={m.user_id} key={m.user_id}>{m.display_name||m.email}</option>)}</select></label><label className="text-xs">Reviewer<select aria-label="Internal reviewer" value={reviewer} onChange={e=>setReviewer(e.target.value)} className="mt-1 w-full rounded border bg-background p-2"><option value="">Choose colleague</option>{members.filter(m=>m.user_id!==engineer&&m.user_id!==userId).map(m=><option value={m.user_id} key={m.user_id}>{m.display_name||m.email}</option>)}</select></label><label className="text-xs">Due date<Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div>
 <Textarea aria-label="Internal review note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Instructions or review decision with reasons…"/>
 <div className="flex flex-wrap gap-2"><Button disabled={busy||!engineer||!reviewer} onClick={()=>void run(async()=>{await workflowAction({action:'request_review',recordId,engineerId:engineer,reviewerId:reviewer,dueDate:due,note});setMessage('Saved draft assigned for internal review.');})}>Request / refresh review</Button>{review?.reviewer_id===userId&&review.status==='pending'&&<><Button disabled={busy||note.trim().length<10} onClick={()=>void run(async()=>{await workflowAction({action:'decide_review',recordId,decision:'approved',note});setMessage('Internal review approved.');})}>Approve saved draft</Button><Button variant="outline" disabled={busy||note.trim().length<10} onClick={()=>void run(async()=>{await workflowAction({action:'decide_review',recordId,decision:'changes_requested',note});setMessage('Changes requested.');})}>Request corrections</Button></>}</div></>}
 </>}
 {!!reviews.length&&<details><summary className="text-sm cursor-pointer">Team review queue ({reviews.length})</summary>{reviews.map(r=>{const record=records.find(x=>x.id===r.record_id);return <button key={r.record_id} className="block w-full border-b p-2 text-left text-xs" onClick={()=>{setRecordId(r.record_id);setEngineer(r.engineer_id);setReviewer(r.reviewer_id);setDue(r.due_date||'');setNote('');}}>{record?.ref||'Submittal'} R{record?.rev??''} · {r.status.replaceAll('_',' ')} · {name(r.engineer_id)} → {name(r.reviewer_id)} · due {r.due_date||'not set'}</button>;})}</details>}
 </div>
 <div className="rounded-xl border p-4 space-y-3"><h2 className="font-semibold">Multi-brand package & transmittal</h2><p className="text-xs text-muted-foreground">Combine 1–12 issued submittals for the same project. Their covers, logos, certificates and internal page references remain intact. The transmittal adds combined page ranges. Limit: 30 MB source PDFs / 600 pages.</p>
 {!issued.length&&<p className="text-sm">No issued PDFs yet. Open a completed draft and choose Mark submitted to freeze its checked PDF before packaging.</p>}
 <div className="max-h-60 overflow-auto space-y-2">{issued.map(r=><label key={r.id} className="flex gap-2 text-sm"><input type="checkbox" checked={selected.includes(r.id)} disabled={busy||!selected.includes(r.id)&&!!project&&r.project.trim().toLowerCase()!==project} onChange={e=>setSelected(prev=>e.target.checked?[...prev,r.id]:prev.filter(id=>id!==r.id))}/>{r.ref} R{r.rev} · {r.project||r.title}</label>)}</div>
 <div className="grid gap-2 sm:grid-cols-3"><Input aria-label="Package title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Package title (defaults to project)"/><Input aria-label="Transmittal recipient" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Recipient / consultant"/><Input aria-label="Transmittal purpose" value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Submission purpose"/></div>
 <p className="text-xs text-muted-foreground">Order follows your selection order. {selected.map(id=>{const r=records.find(r=>r.id===id);return r?`${r.ref} R${r.rev}`:'';}).join(' → ')}</p>
 <Button disabled={busy||selected.length<1||selected.length>12} onClick={()=>void run(async()=>{await workflowAction({action:'create_package',recordIds:selected,title,recipient,purpose});setMessage('Package job saved. You may leave this page; refresh the jobs list to collect the result.');})}>Build package in background</Button>
 </div>
 <div className="space-y-3"><div className="flex justify-between"><h2 className="font-semibold">Package jobs</h2><Button variant="outline" size="sm" disabled={busy} onClick={()=>void run(async()=>{})}>Refresh jobs</Button></div><p className="text-xs text-muted-foreground">Latest 100 jobs. Interrupted jobs can be retried after 10 minutes. Retries rebuild from the saved source PDFs. Oversized packages must be split.</p>{jobs.map(job=>{const stalled=job.status==='running'&&Date.now()-Date.parse(job.updated_at)>600000;return <div key={job.id} className="rounded-xl border p-3 space-y-2"><p className="font-semibold text-sm">{job.title}</p><p className="text-xs">{stalled?'Interrupted — retry available':job.status} · {job.progress}% {job.page_count?`· ${job.page_count} pages`:''}</p>{job.error&&<p className="text-sm text-destructive">{job.error}</p>}<p className="text-xs text-muted-foreground">{job.sources.map(s=>`${s.ref} R${s.rev}`).join(' · ')}</p>
 {job.status==='complete'&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{const result=await workflowAction<{signedUrl:string;expiresAt:string}>({action:'package_link',jobId:job.id});const link=packageLink(result.signedUrl);setLinks(prev=>({...prev,[job.id]:link}));try{await navigator.clipboard.writeText(link);setMessage('Link copied. Valid for 7 days from creation.');}catch{setMessage('Link ready. Select and copy it below.');}})}>Copy package link</Button>}
 {links[job.id]&&<Input aria-label={`Package share link ${job.id.slice(0,8)}`} readOnly value={links[job.id]} onFocus={e=>e.target.select()}/>}
 {(job.status==='failed'||job.status==='queued'||stalled)&&job.created_by===userId&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await workflowAction({action:'retry_package',jobId:job.id});})}>Retry package</Button>}</div>;})}</div>
 {message&&<p role="status" className="rounded-lg bg-muted p-3 text-sm">{message}</p>}
 </div>}</section>;
}
