import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, Download, FileUp, Gauge, Plus, Route, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type Shape='rectangular'|'circular';
type Kind='duct'|'flex'|'elbow90'|'elbow45'|'transition'|'tee-straight'|'tee-branch'|'damper'|'filter'|'coil'|'silencer'|'grille'|'louvre'|'custom';
type Item={id:string;name:string;kind:Kind;shape:Shape;flow:number;width:number;height:number;diameter:number;length:number;qty:number;k:number;fixed:number};
type Path={id:string;name:string;items:Item[]};
const LIB:Record<Kind,{label:string;k:number;fixed?:number}>={duct:{label:'Straight duct',k:0},flex:{label:'Flexible duct',k:0},elbow90:{label:'90° elbow',k:.25},elbow45:{label:'45° elbow',k:.12},transition:{label:'Transition',k:.2},'tee-straight':{label:'Tee — straight path',k:.2},'tee-branch':{label:'Tee — branch path',k:.9},damper:{label:'Volume damper',k:.5},filter:{label:'Filter — manufacturer loss',k:0,fixed:75},coil:{label:'Coil — manufacturer loss',k:0,fixed:100},silencer:{label:'Sound attenuator',k:0,fixed:50},grille:{label:'Grille / diffuser',k:0,fixed:25},louvre:{label:'Louvre',k:0,fixed:35},custom:{label:'Custom component',k:0}};
const id=()=>Math.random().toString(36).slice(2,9);
const item=(kind:Kind='duct'):Item=>({id:id(),name:LIB[kind].label,kind,shape:'rectangular',flow:3600,width:600,height:400,diameter:400,length:kind==='duct'||kind==='flex'?10:0,qty:1,k:LIB[kind].k,fixed:LIB[kind].fixed??0});
const n=(v:unknown,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d};
const rho=(t:number,z:number)=>101325*Math.pow(1-2.25577e-5*Math.max(-500,z),5.2559)/(287.058*(t+273.15));
const mu=(t:number)=>1.716e-5*Math.pow((t+273.15)/273.15,1.5)*(273.15+111)/(t+273.15+111);
const calc=(i:Item,density:number,viscosity:number,rough:number)=>{
 const q=Math.max(0,i.flow)/3600,w=Math.max(1,i.width)/1000,h=Math.max(1,i.height)/1000,d=Math.max(1,i.diameter)/1000;
 const area=i.shape==='circular'?Math.PI*d*d/4:w*h,dh=i.shape==='circular'?d:2*w*h/(w+h),v=q/area,vp=density*v*v/2,re=density*v*dh/viscosity,rr=rough/1000/dh;
 const f=re<=0?0:re<2300?64/re:.25/Math.pow(Math.log10(rr/3.7+5.74/Math.pow(re,.9)),2);
 const friction=(i.kind==='duct'||i.kind==='flex')?f*Math.max(0,i.length)/dh*vp*(i.kind==='flex'?2.5:1)*Math.max(1,i.qty):0;
 const dynamic=(Math.max(0,i.k)*vp+Math.max(0,i.fixed))*Math.max(1,i.qty);
 return {...i,area,dh,v,vp,re,f,friction,dynamic,loss:friction+dynamic};
};
const fmt=(v:number)=>`${v>=100?v.toFixed(0):v.toFixed(1)} Pa`;
const seed:Path[]=[{id:id(),name:'Supply — Critical Route A',items:[item(),{...item('elbow90'),qty:2},item('damper'),item('filter'),item('coil'),item('grille')]}];

export function ESPCalculator(){
 const [paths,setPaths]=useState<Path[]>(seed),[selectedId,setSelectedId]=useState(seed[0].id);
 const [temp,setTemp]=useState(20),[alt,setAlt]=useState(0),[rough,setRough]=useState(.09),[leak,setLeak]=useState(0),[margin,setMargin]=useState(10),[message,setMessage]=useState('');
 const input=useRef<HTMLInputElement>(null),density=rho(temp,alt),viscosity=mu(temp);
 const results=useMemo(()=>paths.map(p=>{const items=p.items.map(i=>calc(i,density,viscosity,rough)),base=items.reduce((s,i)=>s+i.loss,0);return {...p,items,base,total:base*(1+Math.max(0,leak)/100)*(1+Math.max(0,margin)/100)}}),[paths,density,viscosity,rough,leak,margin]);
 const critical=results.reduce((a,b)=>b.total>a.total?b:a,results[0]),selected=results.find(p=>p.id===selectedId)??results[0],max=Math.max(1,...results.map(p=>p.total));
 const updatePath=(patch:Partial<Path>)=>setPaths(ps=>ps.map(p=>p.id===selected.id?{...p,...patch}:p));
 const updateItem=(iid:string,patch:Partial<Item>)=>setPaths(ps=>ps.map(p=>p.id===selected.id?{...p,items:p.items.map(i=>i.id===iid?{...i,...patch}:i)}:p));
 const addPath=()=>{const p={id:id(),name:`Route ${paths.length+1}`,items:[item()]};setPaths(ps=>[...ps,p]);setSelectedId(p.id)};
 const importRows=(rows:Record<string,unknown>[])=>{const groups=new Map<string,Item[]>();rows.forEach(r=>{const name=String(r.route||'Imported route'),raw=String(r.type||r.kind||'duct') as Kind,kind=raw in LIB?raw:'custom';const x={...item(kind),name:String(r.name||LIB[kind].label),kind,shape:String(r.shape).toLowerCase().startsWith('circ')?'circular':'rectangular',flow:n(r.airflow??r.flow),width:n(r.width,500),height:n(r.height,300),diameter:n(r.diameter,315),length:n(r.length),qty:Math.max(1,n(r.quantity??r.qty,1)),k:n(r.k,LIB[kind].k),fixed:n(r.fixedLoss??r.fixed,LIB[kind].fixed??0)} as Item;groups.set(name,[...(groups.get(name)||[]),x])});const next=[...groups].map(([name,items])=>({id:id(),name,items}));if(!next.length)throw Error('No valid rows');setPaths(next);setSelectedId(next[0].id);setMessage(`${next.length} route(s) imported and calculated. Confirm flow splits, geometry and K values.`)};
 const upload=async(file?:File)=>{if(!file)return;try{const text=await file.text();if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(text);importRows(Array.isArray(data)?data:data.routes.flatMap((p:any)=>p.items.map((i:any)=>({...i,route:p.name}))));}else{const ls=text.split(/\r?\n/).filter(Boolean),heads=(ls.shift()||'').split(',').map(x=>x.trim());importRows(ls.map(line=>Object.fromEntries(heads.map((h,j)=>[h,line.split(',')[j]?.trim()||'']))));}}catch(e){setMessage(`Import failed: ${e instanceof Error?e.message:'invalid file'}`)}};
 const template=()=>{const text='route,name,type,shape,airflow,width,height,diameter,length,quantity,k,fixedLoss\nSupply A,Main duct,duct,rectangular,5000,800,500,,18,1,0,0\nSupply A,Elbows,elbow90,rectangular,5000,800,500,,0,2,0.25,0\nSupply A,Dirty filter,filter,rectangular,5000,800,500,,0,1,0,120\nBranch B,Branch duct,duct,circular,1200,,,315,12,1,0,0';const u=URL.createObjectURL(new Blob([text],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='KINAIR-ESP-route-template.csv';a.click();URL.revokeObjectURL(u)};
 return <div className="space-y-5">
  <Card className="overflow-hidden border-primary/20"><CardHeader className="bg-gradient-to-r from-slate-950 to-blue-950 text-white"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><Badge className="mb-3 bg-cyan-400 text-slate-950 hover:bg-cyan-400">KINAIR Engineering Intelligence</Badge><CardTitle className="flex gap-2 text-2xl"><Route className="text-cyan-300"/>Intelligent ESP Route Calculator</CardTitle><CardDescription className="mt-2 text-slate-300">Calculate every supply, return or exhaust path and automatically identify the governing fan duty.</CardDescription></div><div className="rounded-xl border border-white/20 bg-white/10 px-5 py-3"><small className="block text-slate-300">CRITICAL ROUTE DESIGN ESP</small><b className="text-3xl text-cyan-300">{critical?fmt(critical.total):'0 Pa'}</b><span className="block">{critical?.name}</span></div></div></CardHeader></Card>
  <Tabs defaultValue="network"><TabsList className="grid h-auto w-full grid-cols-3"><TabsTrigger value="network">Route network</TabsTrigger><TabsTrigger value="import">Import route</TabsTrigger><TabsTrigger value="basis">Engineering basis</TabsTrigger></TabsList>
   <TabsContent value="network" className="space-y-5">
    <Card><CardHeader><CardTitle className="text-lg">Design conditions</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
     {([['Temperature °C',temp,setTemp],['Altitude m',alt,setAlt],['Roughness ε mm',rough,setRough],['Leakage %',leak,setLeak],['Design margin %',margin,setMargin]] as const).map(([label,value,setter])=><div key={label}><Label>{label}</Label><Input type="number" step="0.01" value={value} onChange={e=>setter(n(e.target.value))}/></div>)}
     <div className="flex flex-wrap gap-2 sm:col-span-2 lg:col-span-5"><Badge variant="outline">ρ {density.toFixed(3)} kg/m³</Badge><Badge variant="outline">Darcy–Weisbach</Badge><Badge variant="outline">Swamee–Jain</Badge><Badge variant="outline">K × velocity pressure</Badge></div>
    </CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[290px_1fr]">
     <Card className="h-fit"><CardHeader><div className="flex justify-between"><CardTitle className="text-lg">Routes</CardTitle><Button size="sm" onClick={addPath}><Plus className="mr-1 h-4 w-4"/>Route</Button></div></CardHeader><CardContent className="space-y-2">{results.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)} className={`w-full rounded-xl border p-3 text-left ${p.id===selected.id?'border-primary bg-primary/5':''}`}><div className="flex justify-between gap-2"><b className="truncate">{p.name}</b>{p.id===critical.id&&<Badge className="bg-amber-500">Critical</Badge>}</div><div className="my-2 h-2 rounded bg-muted"><div className="h-2 rounded bg-gradient-to-r from-cyan-500 to-blue-700" style={{width:`${Math.max(4,p.total/max*100)}%`}}/></div><span className="text-sm">{fmt(p.total)}</span></button>)}</CardContent></Card>
     <Card><CardHeader><div className="flex gap-2"><Input value={selected.name} onChange={e=>updatePath({name:e.target.value})}/><Button variant="outline" disabled={paths.length===1} onClick={()=>{const next=paths.filter(p=>p.id!==selected.id);setPaths(next);setSelectedId(next[0].id)}}><Trash2 className="h-4 w-4"/></Button></div></CardHeader><CardContent className="space-y-4">
      <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1080px] text-sm"><thead className="bg-slate-900 text-white"><tr>{['Component','Type','Flow m³/h','Shape / size mm','Length / Qty','K / Fixed Pa','Velocity','Loss',''].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{selected.items.map(i=><tr key={i.id} className="border-t align-top">
       <td className="p-2"><Input className="w-40" value={i.name} onChange={e=>updateItem(i.id,{name:e.target.value})}/></td>
       <td className="p-2"><Select value={i.kind} onValueChange={(kind:Kind)=>updateItem(i.id,{kind,name:LIB[kind].label,k:LIB[kind].k,fixed:LIB[kind].fixed??0})}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(LIB).map(([k,v])=><SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select></td>
       <td className="p-2"><Input className="w-28" type="number" value={i.flow} onChange={e=>updateItem(i.id,{flow:n(e.target.value)})}/></td>
       <td className="p-2"><Select value={i.shape} onValueChange={(shape:Shape)=>updateItem(i.id,{shape})}><SelectTrigger className="mb-1 w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="rectangular">Rectangular</SelectItem><SelectItem value="circular">Circular</SelectItem></SelectContent></Select>{i.shape==='circular'?<Input className="w-36" type="number" value={i.diameter} onChange={e=>updateItem(i.id,{diameter:n(e.target.value)})}/>:<div className="flex gap-1"><Input className="w-[68px]" type="number" value={i.width} onChange={e=>updateItem(i.id,{width:n(e.target.value)})}/><Input className="w-[68px]" type="number" value={i.height} onChange={e=>updateItem(i.id,{height:n(e.target.value)})}/></div>}</td>
       <td className="p-2"><div className="flex gap-1"><Input className="w-20" type="number" value={i.length} onChange={e=>updateItem(i.id,{length:n(e.target.value)})}/><Input className="w-16" type="number" value={i.qty} onChange={e=>updateItem(i.id,{qty:Math.max(1,n(e.target.value,1))})}/></div></td>
       <td className="p-2"><div className="flex gap-1"><Input className="w-20" type="number" step=".01" value={i.k} onChange={e=>updateItem(i.id,{k:n(e.target.value)})}/><Input className="w-20" type="number" value={i.fixed} onChange={e=>updateItem(i.id,{fixed:n(e.target.value)})}/></div></td>
       <td className="p-3"><b>{i.v.toFixed(2)} m/s</b>{i.v>8&&<small className="block text-amber-600">High velocity</small>}</td><td className="p-3"><b className="text-primary">{fmt(i.loss)}</b><small className="block text-muted-foreground">VP {i.vp.toFixed(1)} Pa</small></td><td className="p-2"><Button size="icon" variant="ghost" onClick={()=>updatePath({items:selected.items.filter(x=>x.id!==i.id)})}><Trash2 className="h-4 w-4"/></Button></td>
      </tr>)}</tbody></table></div>
      <div className="flex flex-wrap gap-2">{(['duct','elbow90','transition','tee-branch','damper','filter','coil','silencer','grille','custom'] as Kind[]).map(k=><Button key={k} size="sm" variant="outline" onClick={()=>updatePath({items:[...selected.items,item(k)]})}><Plus className="mr-1 h-3 w-3"/>{LIB[k].label}</Button>)}</div>
      <div className="grid gap-3 sm:grid-cols-4">{[['Route loss',fmt(selected.base)],['Leakage',`${leak}%`],['Margin',`${margin}%`],['Design ESP',fmt(selected.total)]].map(([a,b])=><div key={a} className="rounded-xl border bg-muted/30 p-4"><span className="text-sm text-muted-foreground">{a}</span><b className="block text-2xl">{b}</b></div>)}</div>
     </CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle className="flex gap-2 text-lg"><Gauge className="text-primary"/>Fan duty summary</CardTitle></CardHeader><CardContent>{results.map(p=><div key={p.id} className="mb-3 grid grid-cols-[minmax(100px,220px)_1fr_85px] gap-3"><span className="truncate">{p.name}</span><div className="h-4 rounded bg-muted"><div className={`h-4 rounded ${p.id===critical.id?'bg-amber-500':'bg-blue-600'}`} style={{width:`${p.total/max*100}%`}}/></div><b className="text-right">{fmt(p.total)}</b></div>)}</CardContent></Card>
   </TabsContent>
   <TabsContent value="import"><Card><CardHeader><CardTitle className="flex gap-2"><FileUp/>Import route schedule</CardTitle><CardDescription>Upload CSV or JSON exported from Excel, BIM or a duct take-off. Every route is calculated independently.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="rounded-2xl border-2 border-dashed p-8 text-center"><FileUp className="mx-auto mb-3 h-10 w-10 text-primary"/><p>Include route, component type, airflow and section dimensions.</p><input ref={input} className="hidden" type="file" accept=".csv,.json" onChange={e=>upload(e.target.files?.[0])}/><div className="mt-4 flex justify-center gap-2"><Button onClick={()=>input.current?.click()}><FileUp className="mr-2 h-4 w-4"/>Upload & calculate</Button><Button variant="outline" onClick={template}><Download className="mr-2 h-4 w-4"/>Template</Button></div></div>{message&&<div className="rounded-xl border bg-muted/30 p-4">{message}</div>}<div className="flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><AlertTriangle className="shrink-0"/><p><b>Drawing intelligence requires engineering confirmation.</b> PDF/image/CAD recognition alone cannot safely infer hidden offsets, airflow splits, exact fitting geometry or manufacturer losses. This verified route engine is the calculation core for the drawing-extraction stage.</p></div></CardContent></Card></TabsContent>
   <TabsContent value="basis"><Card><CardHeader><CardTitle>Transparent engineering basis</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{[['Straight duct','Darcy–Weisbach Δp = f·L/Dh·ρV²/2 with hydraulic diameter and Reynolds-dependent friction.'],['Fittings','Δp = K·ρV²/2 using the actual referenced section velocity.'],['Branches','Main and branch paths carry their own airflow, size and loss coefficient. Parallel branch losses are not added.'],['Equipment','Enter manufacturer clean/design/final losses for filters, coils, silencers, grilles and louvres.'],['Air conditions','Density corrects for temperature and altitude; viscosity is temperature corrected.'],['Fan selection','The highest-loss complete path governs required external static pressure.']].map(([a,b])=><div key={a} className="rounded-xl border p-4"><b>{a}</b><p className="mt-1 text-sm text-muted-foreground">{b}</p></div>)}</CardContent></Card></TabsContent>
  </Tabs>
 </div>
}