import { createClient } from "npm:@supabase/supabase-js@2.89.0";
import { PDFDocument, StandardFonts, degrees, rgb } from "npm:pdf-lib@1.17.1";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const A4:[number,number]=[595.28,841.89];const blue=rgb(.02,.32,.62);const pale=rgb(.94,.98,1);const grey=rgb(.38,.43,.5);
const safe=(v:unknown,max=80)=>String(v??"-").replace(/[\r\n]+/g," ").slice(0,max);
function wrap(text:string,max:number){const words=text.split(/\s+/);const out:string[]=[];let line="";for(const w of words){if((line+" "+w).trim().length>max){if(line)out.push(line);line=w}else line=(line+" "+w).trim()}if(line)out.push(line);return out}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 try{
  const auth=req.headers.get("Authorization");if(!auth)throw new Error("Authentication required");
  const scoped=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});
  const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const {packageId,preview=false}=await req.json();
  const {data:p,error:pe}=await scoped.from("submittal_packages").select("*").eq("id",packageId).single();if(pe||!p)throw pe??new Error("Package not found");
  const {data:items,error:ie}=await scoped.from("submittal_package_items").select("*").eq("package_id",packageId).eq("is_included",true).order("sort_order");if(ie)throw ie;
  // Missing index sections are allowed: keep their divider pages and generate with available documents.
  const usable=(items??[]).filter((x:any)=>x.storage_path&&x.validation_state!=="missing");
  const grouped=new Map<string,any[]>();for(const item of usable){const key=item.section_name||"Supporting Documents";if(!grouped.has(key))grouped.set(key,[]);grouped.get(key)!.push(item)}
  const loaded=new Map<string,PDFDocument>();for(const item of usable){if(loaded.has(item.storage_path))continue;const {data:b,error:be}=await admin.storage.from("submittal-control").download(item.storage_path);if(be||!b)throw new Error(`Unable to load ${safe(item.display_name)}: ${be?.message||"file missing"}`);try{loaded.set(item.storage_path,await PDFDocument.load(await b.arrayBuffer(),{ignoreEncryption:false}))}catch{throw new Error(`PDF cannot be assembled: ${safe(item.display_name)}`)}}
  const out=await PDFDocument.create();const font=await out.embedFont(StandardFonts.Helvetica);const bold=await out.embedFont(StandardFonts.HelveticaBold);
  const selectedTemplateIds=p.cover_details?.template_ids||{};const ids=Object.values(selectedTemplateIds).filter(Boolean) as string[];const templateByType=new Map<string,any>();const templateDocs=new Map<string,PDFDocument>();let logoAsset:{bytes:ArrayBuffer;path:string}|null=null;
  if(ids.length){const {data:templateRows}=await scoped.from("submittal_templates").select("*").eq("tenant_id",p.tenant_id).in("id",ids);for(const row of templateRows??[]){const {data:asset}=await admin.storage.from("submittal-control").download(row.storage_path);if(!asset)continue;const bytes=await asset.arrayBuffer();templateByType.set(row.template_type,row);if(["cover","index","divider"].includes(row.template_type)){try{templateDocs.set(row.template_type,await PDFDocument.load(bytes,{ignoreEncryption:true}))}catch{/* use standard layout when uploaded asset is not a PDF */}}else if(row.template_type==="logo")logoAsset={bytes,path:row.storage_path}}}
  const addDesignedPage=async(type:"cover"|"index"|"divider")=>{const source=templateDocs.get(type);if(source){const [page]=await out.copyPages(source,[0]);return out.addPage(page)}return out.addPage(A4)};
  const allSectionNames=Array.isArray(p.index_sections)&&p.index_sections.length?p.index_sections.map((x:any)=>x.name):[...grouped.keys()];
  const pqLetterName=p.package_type==="pq"?allSectionNames.find((name:string)=>/pre[ -]?qualification.*letter|pq.*letter/i.test(name)):undefined;
  const sectionNames=pqLetterName?allSectionNames.filter((name:string)=>name!==pqLetterName):allSectionNames;
  const pqIntroItems=pqLetterName?(grouped.get(pqLetterName)||[]):[];
  const appendItem=async(item:any)=>{const source=loaded.get(item.storage_path)!;for(const sourcePage of source.getPages()){const sw=sourcePage.getWidth(),sh=sourcePage.getHeight(),landscape=sw>sh;const size:[number,number]=landscape?[A4[1],A4[0]]:A4;const target=out.addPage(size);const embedded=await out.embedPage(sourcePage);const scale=Math.min((size[0]-28)/sw,(size[1]-36)/sh);const w=sw*scale,h=sh*scale;target.drawPage(embedded,{x:(size[0]-w)/2,y:(size[1]-h)/2+6,width:w,height:h});target.drawRectangle({x:8,y:8,width:size[0]-16,height:size[1]-16,borderWidth:.5,borderColor:rgb(.82,.86,.9)})}};
  if(p.package_type!=="pq"){
   const cover=await addDesignedPage("cover");if(!templateDocs.has("cover")){cover.drawRectangle({x:0,y:748,width:A4[0],height:94,color:blue});cover.drawText("KINAIR",{x:42,y:790,size:28,font:bold,color:rgb(1,1,1)});cover.drawText("ENGINEERED AIR MOVEMENT",{x:43,y:772,size:8,font,color:rgb(.8,.93,1)})}
   if(logoAsset){try{const img=logoAsset.path.toLowerCase().endsWith(".png")?await out.embedPng(logoAsset.bytes):await out.embedJpg(logoAsset.bytes);const scale=Math.min(105/img.width,55/img.height);cover.drawImage(img,{x:445,y:770,width:img.width*scale,height:img.height*scale})}catch{/* invalid logo ignored */}}
   const packageTitle=p.package_type==="om"?"OPERATION & MAINTENANCE":p.package_type==="pq"?"PRE-QUALIFICATION":"MATERIAL";cover.drawText(packageTitle+" SUBMITTAL",{x:42,y:690,size:23,font:bold,color:blue});cover.drawRectangle({x:42,y:672,width:82,height:4,color:rgb(.05,.7,.84)});
   const extra=p.cover_details||{};const labels=extra.field_labels||{};const additional=Array.isArray(extra.additional_fields)?extra.additional_fields.filter((x:any)=>x?.label):[];const coverValues:Record<string,any>={project_name:[labels.project_name||"PROJECT NAME",extra.project_name||p.project_name],material:[labels.material||"MATERIAL / SUBMITTAL FOR",extra.material||p.material],client_name:[labels.client_name||"CLIENT NAME",extra.client_name||p.client_name],consultant_name:[labels.consultant_name||"MEP CONSULTANT",extra.consultant_name||p.consultant_name],main_contractor_name:[labels.main_contractor_name||"MAIN CONTRACTOR",extra.main_contractor_name||p.main_contractor_name],subcontractor_name:[labels.subcontractor_name||"MEP CONTRACTOR",extra.subcontractor_name||p.subcontractor_name],supplier_name:[labels.supplier_name||"SUPPLIER NAME",extra.supplier_name||p.submitted_by_company||"KINETICS MIDDLE EAST LLC"],brand_name:[labels.brand_name||"BRAND NAME",extra.brand_name||"KINAIR"]};const defaultOrder=Object.keys(coverValues);const fieldOrder=Array.isArray(extra.field_order)?[...new Set(extra.field_order.filter((key:any)=>coverValues[key]))]:defaultOrder;for(const key of defaultOrder)if(!fieldOrder.includes(key))fieldOrder.push(key);const fields:any[]=[...fieldOrder.map((key:string)=>coverValues[key]),...additional.map((x:any)=>[safe(x.label,40).toUpperCase(),x.value]),["REFERENCE",p.reference],["REVISION",`R${p.revision}`],["DATE",p.submission_date]];
   let y=624;for(const [k,v] of fields){if(!v)continue;cover.drawText(k,{x:44,y,size:8,font:bold,color:grey});const lines=wrap(safe(v,120),62);lines.slice(0,2).forEach((line,j)=>cover.drawText(line,{x:174,y:y-j*13,size:10,font,color:rgb(.08,.12,.18)}));cover.drawLine({start:{x:44,y:y-10-lines.length*3},end:{x:550,y:y-10-lines.length*3},thickness:.4,color:rgb(.83,.86,.9)});y-=38+Math.max(0,lines.length-1)*10}
   if(p.apply_stamp){const {data:stamps}=await scoped.from("submittal_templates").select("storage_path").eq("tenant_id",p.tenant_id).eq("template_type","stamp").order("created_at",{ascending:false}).limit(1);if(stamps?.[0]){const {data:s}=await admin.storage.from("submittal-control").download(stamps[0].storage_path);if(s){const bytes=await s.arrayBuffer();try{const img=stamps[0].storage_path.toLowerCase().endsWith(".png")?await out.embedPng(bytes):await out.embedJpg(bytes);const scale=Math.min(110/img.width,75/img.height);cover.drawImage(img,{x:430,y:48,width:img.width*scale,height:img.height*scale})}catch{/* invalid stamp ignored */}}}}
  }
  for(const item of pqIntroItems)await appendItem(item);
const tocPages=Math.max(1,Math.ceil(sectionNames.length/22));const starts=new Map<string,number>();const pqIntroPages=pqIntroItems.reduce((n:number,item:any)=>n+(loaded.get(item.storage_path)?.getPageCount()||0),0);let cursor=(p.package_type==="pq"?pqIntroPages:1)+tocPages+1;for(const name of sectionNames){starts.set(name,cursor);const docs=grouped.get(name)||[];cursor+=1+docs.reduce((n,item)=>n+(loaded.get(item.storage_path)?.getPageCount()||0),0)}
  for(let t=0;t<tocPages;t++){const page=await addDesignedPage("index");if(!templateDocs.has("index")){page.drawRectangle({x:0,y:780,width:A4[0],height:62,color:blue});page.drawText("TABLE OF CONTENTS",{x:42,y:803,size:18,font:bold,color:rgb(1,1,1)})}let ty=738;sectionNames.slice(t*22,(t+1)*22).forEach((name:string,i:number)=>{const no=t*22+i+1;page.drawRectangle({x:40,y:ty-8,width:515,height:24,color:i%2===0?rgb(.92,.96,1):rgb(.97,.98,1)});page.drawRectangle({x:40,y:ty-8,width:5,height:24,color:blue});page.drawText(String(no).padStart(2,"0"),{x:52,y:ty,size:9,font:bold,color:blue});page.drawText(safe(name,64),{x:86,y:ty,size:10,font,color:rgb(.08,.12,.18)});page.drawText(String(starts.get(name)||"-"),{x:525,y:ty,size:10,font:bold,color:blue});ty-=30})}
  for(const name of sectionNames){const divider=await addDesignedPage("divider");if(!templateDocs.has("divider")){divider.drawRectangle({x:0,y:0,width:A4[0],height:A4[1],color:pale});divider.drawRectangle({x:0,y:0,width:18,height:A4[1],color:blue})}divider.drawText(String(sectionNames.indexOf(name)+1).padStart(2,"0"),{x:55,y:490,size:16,font:bold,color:rgb(.05,.7,.84)});for(const [j,line] of wrap(safe(name,120).toUpperCase(),32).entries())divider.drawText(line,{x:55,y:445-j*32,size:24,font:bold,color:blue});divider.drawText("KINAIR CONTROLLED SUBMITTAL",{x:55,y:70,size:8,font:bold,color:grey});
   for(const item of grouped.get(name)||[])await appendItem(item);
  }
  const total=out.getPageCount();out.getPages().forEach((pg,i)=>{const w=pg.getWidth();pg.drawText(`KINAIR  |  ${safe(p.reference||p.project_name,45)}`,{x:18,y:10,size:7,font,color:grey});pg.drawText(`${i+1} / ${total}`,{x:w-48,y:10,size:7,font:bold,color:grey})});
  const bytes=await out.save();const path=`${p.tenant_id}/generated/${p.id}-R${p.revision}.pdf`;
  if(!preview){const {error:ue}=await admin.storage.from("submittal-control").upload(path,bytes,{contentType:"application/pdf",upsert:true});if(ue)throw ue;const {error:updateError}=await scoped.from("submittal_packages").update({status:"generated",output_storage_path:path,failure_message:null,updated_at:new Date().toISOString()}).eq("id",p.id);if(updateError)throw updateError}
  return new Response(bytes,{headers:{...cors,"Content-Type":"application/pdf","Content-Disposition":`${preview?"inline":"attachment"}; filename="${safe(p.reference||"submittal")}-R${p.revision}.pdf"`}});
 }catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:"Generation failed"}),{status:400,headers:{...cors,"Content-Type":"application/json"}})}
});
